import instrument from '../../libraries/instrument';
import { QuestionObjectType } from '../../libraries/interfaces';


export const questions: QuestionObjectType = {
    'reg': {
        name: 'reg',
        type: 'select',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 0,
        active: function() {return(true)},
        skip: false
    },
    'dis': {
        name: 'dis',
        type: 'select',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 1,
        active: function() {return(true)},
        skip: false
    },
    'data': {
        name: 'data',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: true,
        readonly: true,
        order: 2,
        active: function() {return(true)},
        skip: false
    },
    'omr1': {
        name: 'omr1',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 3,
        active: function() {return(true)},
        skip: false
    },
    'omr2': {
        name: 'omr2',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 4,
        active: function() {return(true)},
        skip: false
    },
    'omr3': {
        name: 'omr3',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 5,
        active: function() {return(true)},
        skip: false
    },
    'omr4': {
        name: 'omr4',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 6,
        active: function() {return(true)},
        skip: false
    },
    'omr5': {
        name: 'omr5',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 7,
        active: function() {return(true)},
        skip: false
    },
    'omr6': {
        name: 'omr6',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 8,
        active: function() {return(true)},
        skip: false
    },
    'omr7': {
        name: 'omr7',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 9,
        active: function() {return(true)},
        skip: false
    },
    'omr9': {
        name: 'omr9',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 10,
        active: function() {return(true)},
        skip: false
    },
    'pi1': {
        name: 'pi1',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 11,
        active: function() {return(true)},
        skip: false
    },
    'pi1a': {
        name: 'pi1a',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 12,
        active: function() {return(true)},
        skip: false
    },
    'pi1b': {
        name: 'pi1b',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 13,
        active: function() {return(true)},
        skip: false
    },
    'pi1c': {
        name: 'pi1c',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 14,
        active: function() {return(true)},
        skip: false
    },
    'pi2': {
        name: 'pi2',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 15,
        active: function() {return(true)},
        skip: false
    },
    'pi3': {
        name: 'pi3',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 16,
        active: function() {return(true)},
        skip: false
    },
    'pi3a': {
        name: 'pi3a',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: true,
        order: 17,
        active: function() {return(true)},
        skip: false
    },
    'pi4a_dk': {
        name: 'pi4a_dk',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 18,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'pi4b': {
        name: 'pi4b',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 19,
        active: function() {return(Number(instrument.questions.pi4a_dk.value) == 0)},
        skip: false
    },
    'pi4c': {
        name: 'pi4c',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 20,
        active: function() {return(Number(instrument.questions.pi4b.value) > 0)},
        skip: false
    },
    'pi5': {
        name: 'pi5',
        type: 'select',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 21,
        active: function() {return(true)},
        skip: false
    },
    'pi6r': {
        name: 'pi6r',
        type: 'select',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 22,
        active: function() {return(true)},
        skip: false
    },
    'pi6d': {
        name: 'pi6d',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 23,
        active: function() {return(Number(instrument.questions.pi6r.value) > 0)},
        skip: false
    },
    'pi6i': {
        name: 'pi6i',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 24,
        active: function() {return(Number(instrument.questions.pi6d.value) > 0)},
        skip: false
    },
    'pi6n': {
        name: 'pi6n',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 25,
        active: function() {return(Number(instrument.questions.pi6i.value) == 999)},
        skip: false
    },
    'pi6t': {
        name: 'pi6t',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 26,
        active: function() {return(Number(instrument.questions.pi6i.value) == 999)},
        skip: false
    },
    'pi7': {
        name: 'pi7',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 27,
        active: function() {return(true)},
        skip: false
    },
    'pi8': {
        name: 'pi8',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 28,
        active: function() {return(true)},
        skip: false
    },
    'pi9a': {
        name: 'pi9a',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 29,
        active: function() {return(true)},
        skip: false
    },
    'pi9c': {
        name: 'pi9c',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 30,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2 || Number(instrument.questions.pi9a.value) == 3)},
        skip: false
    },
    'pi9d': {
        name: 'pi9d',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 31,
        active: function() {return(Number(instrument.questions.pi9c.value) > 0)},
        skip: false
    },
    'pi9h': {
        name: 'pi9h',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 32,
        active: function() {return(Number(instrument.questions.pi9d.value) > 0)},
        skip: false
    },
    'pi9m': {
        name: 'pi9m',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 33,
        active: function() {return(Number(instrument.questions.pi9h.value) > 0)},
        skip: false
    },
    'pi9i': {
        name: 'pi9i',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: true,
        readonly: true,
        order: 34,
        active: function() {return(true)},
        skip: false
    },
    'pi9e': {
        name: 'pi9e',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 35,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2 || Number(instrument.questions.pi9a.value) == 3)},
        skip: false
    },
    'pi9f': {
        name: 'pi9f',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 36,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2 || Number(instrument.questions.pi9a.value) == 3)},
        skip: false
    },
    'pi9g': {
        name: 'pi9g',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 37,
        active: function() {return(Number(instrument.questions.pi9a.value) == 3)},
        skip: false
    },
    'pi10': {
        name: 'pi10',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 38,
        active: function() {return(true)},
        skip: false
    },
    'pi10a': {
        name: 'pi10a',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 39,
        active: function() {return(Number(instrument.questions.pi10.value) == 1)},
        skip: false
    },
    'pi10b': {
        name: 'pi10b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 40,
        active: function() {return(Number(instrument.questions.pi10.value) == 1 && Number(instrument.questions.pi10a.value) > 0)},
        skip: false
    },
    'pr1': {
        name: 'pr1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 41,
        active: function() {return(true)},
        skip: false
    },
    'pr2': {
        name: 'pr2',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 42,
        active: function() {return(Number(instrument.questions.pr1.value) == 1)},
        skip: false
    },
    'pr3': {
        name: 'pr3',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 43,
        active: function() {return(Number(instrument.questions.pr1.value) == 1 && (Number(instrument.questions.pr2.value) == 2 || Number(instrument.questions.pr2.value) == 3))},
        skip: false
    },
    'pr4': {
        name: 'pr4',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 44,
        active: function() {return(Number(instrument.questions.pr1.value) == 1 && (Number(instrument.questions.pr2.value) == 2 || Number(instrument.questions.pr2.value) == 3))},
        skip: false
    },
    'lv1': {
        name: 'lv1',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 45,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false
    },
    'lv1_other': {
        name: 'lv1_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 46,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv1.value) == 7)},
        skip: false
    },
    'lv2_1': {
        name: 'lv2_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 47,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv2_2': {
        name: 'lv2_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 48,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv2_3': {
        name: 'lv2_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 49,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv2_4': {
        name: 'lv2_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 50,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv2_5': {
        name: 'lv2_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 51,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv2_6': {
        name: 'lv2_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 52,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv2_7': {
        name: 'lv2_7',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 53,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv2_8': {
        name: 'lv2_8',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 54,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv2_9': {
        name: 'lv2_9',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 55,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false,
        checked: 0
    },
    'lv3': {
        name: 'lv3',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 56,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv2_1.value) == 0)},
        skip: false
    },
    'lv4': {
        name: 'lv4',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 57,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false
    },
    'lv5': {
        name: 'lv5',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 58,
        active: function() {return(Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2)},
        skip: false
    },
    'lv6_1': {
        name: 'lv6_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 59,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 1)},
        skip: false,
        checked: 0
    },
    'lv6_2': {
        name: 'lv6_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 60,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 1)},
        skip: false,
        checked: 0
    },
    'lv6_3': {
        name: 'lv6_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 61,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 1)},
        skip: false,
        checked: 0
    },
    'lv6_4': {
        name: 'lv6_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 62,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 1)},
        skip: false,
        checked: 0
    },
    'lv6_5': {
        name: 'lv6_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 63,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 1)},
        skip: false,
        checked: 0
    },
    'lv6_6': {
        name: 'lv6_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 64,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 1)},
        skip: false,
        checked: 0
    },
    'lv6_6_other': {
        name: 'lv6_6_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 65,
        active: function() {return((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 1 && Number(instrument.questions.lv6_6.value) == 1)},
        skip: false
    },
    'lv6b': {
        name: 'lv6b',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 66,
        active: function() {return(((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 1 && Number(instrument.questions.lv6_2.value) == 0) || ((Number(instrument.questions.pi9a.value) == 1 || Number(instrument.questions.pi9a.value) == 2) && Number(instrument.questions.lv5.value) == 0))},
        skip: false
    },
    'lv7': {
        name: 'lv7',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 67,
        active: function() {return(Number(instrument.questions.pi9a.value) == 3)},
        skip: false
    },
    'lv8': {
        name: 'lv8',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 68,
        active: function() {return(Number(instrument.questions.pi9a.value) == 3)},
        skip: false
    },
    'lv9': {
        name: 'lv9',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 69,
        active: function() {return(true)},
        skip: true
    },
    'ee1': {
        name: 'ee1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 70,
        active: function() {return(true)},
        skip: false
    },
    'ee2': {
        name: 'ee2',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 71,
        active: function() {return(Number(instrument.questions.ee1.value) == 5)},
        skip: false
    },
    'ee2_other': {
        name: 'ee2_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 72,
        active: function() {return(Number(instrument.questions.ee1.value) == 5 && Number(instrument.questions.ee2.value) == 4)},
        skip: false
    },
    'ee3': {
        name: 'ee3',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 73,
        active: function() {return(true)},
        skip: false
    },
    'ee4_1': {
        name: 'ee4_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 74,
        active: function() {return(Number(instrument.questions.ee3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee4_2': {
        name: 'ee4_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 75,
        active: function() {return(Number(instrument.questions.ee3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee4_3': {
        name: 'ee4_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 76,
        active: function() {return(Number(instrument.questions.ee3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee4_4': {
        name: 'ee4_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 77,
        active: function() {return(Number(instrument.questions.ee3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee4_5': {
        name: 'ee4_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 78,
        active: function() {return(Number(instrument.questions.ee3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee4_6': {
        name: 'ee4_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 79,
        active: function() {return(Number(instrument.questions.ee3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee4_6_other': {
        name: 'ee4_6_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 80,
        active: function() {return(Number(instrument.questions.ee3.value) == 1 && Number(instrument.questions.ee4_6.value) == 1)},
        skip: false
    },
    'ee5': {
        name: 'ee5',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 81,
        active: function() {return(true)},
        skip: false
    },
    'ee5_other': {
        name: 'ee5_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 82,
        active: function() {return(Number(instrument.questions.ee5.value) == 9)},
        skip: false
    },
    'ee6': {
        name: 'ee6',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 83,
        active: function() {return(Number(instrument.questions.ee5.value) == 5)},
        skip: false
    },
    'ee7': {
        name: 'ee7',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 84,
        active: function() {return(Number(instrument.questions.ee5.value) == 5 && Number(instrument.questions.ee6.value) == 1)},
        skip: false
    },
    'ee8': {
        name: 'ee8',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 85,
        active: function() {return(true)},
        skip: false
    },
    'ee9': {
        name: 'ee9',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 86,
        active: function() {return(true)},
        skip: false
    },
    'ee10_1': {
        name: 'ee10_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 87,
        active: function() {return(Number(instrument.questions.ee9.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee10_2': {
        name: 'ee10_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 88,
        active: function() {return(Number(instrument.questions.ee9.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee10_3': {
        name: 'ee10_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 89,
        active: function() {return(Number(instrument.questions.ee9.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee10_4': {
        name: 'ee10_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 90,
        active: function() {return(Number(instrument.questions.ee9.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee10_5': {
        name: 'ee10_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 91,
        active: function() {return(Number(instrument.questions.ee9.value) == 1)},
        skip: false,
        checked: 0
    },
    'ee10_5_other': {
        name: 'ee10_5_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 92,
        active: function() {return(Number(instrument.questions.ee9.value) == 1 && Number(instrument.questions.ee10_5.value) == 1)},
        skip: false
    },
    'ee11_1': {
        name: 'ee11_1',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 93,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_2': {
        name: 'ee11_2',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 94,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_3': {
        name: 'ee11_3',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 95,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_4': {
        name: 'ee11_4',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 96,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_5': {
        name: 'ee11_5',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 97,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_6': {
        name: 'ee11_6',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 98,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_7': {
        name: 'ee11_7',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 99,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_8': {
        name: 'ee11_8',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 100,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_9': {
        name: 'ee11_9',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 101,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_10': {
        name: 'ee11_10',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 102,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_11': {
        name: 'ee11_11',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 103,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_12': {
        name: 'ee11_12',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 104,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee11_12_other': {
        name: 'ee11_12_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 105,
        active: function() {return(Number(instrument.questions.ee11_12.value) == 1)},
        skip: false
    },
    'ee12_dk': {
        name: 'ee12_dk',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 106,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ee12': {
        name: 'ee12',
        type: 'double',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 107,
        active: function() {return(Number(instrument.questions.ee12_dk.value) == 0)},
        skip: false
    },
    'ee13': {
        name: 'ee13',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 108,
        active: function() {return(true)},
        skip: true
    },
    'he1': {
        name: 'he1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 109,
        active: function() {return(true)},
        skip: false
    },
    'he2': {
        name: 'he2',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 110,
        active: function() {return(true)},
        skip: false
    },
    'he3': {
        name: 'he3',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 111,
        active: function() {return(true)},
        skip: false
    },
    'he4_1': {
        name: 'he4_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 112,
        active: function() {return(Number(instrument.questions.he3.value) == 1)},
        skip: false,
        checked: 0
    },
    'he4_2': {
        name: 'he4_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 113,
        active: function() {return(Number(instrument.questions.he3.value) == 1)},
        skip: false,
        checked: 0
    },
    'he4_3': {
        name: 'he4_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 114,
        active: function() {return(Number(instrument.questions.he3.value) == 1)},
        skip: false,
        checked: 0
    },
    'he4_4': {
        name: 'he4_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 115,
        active: function() {return(Number(instrument.questions.he3.value) == 1)},
        skip: false,
        checked: 0
    },
    'he4_5': {
        name: 'he4_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 116,
        active: function() {return(Number(instrument.questions.he3.value) == 1)},
        skip: false,
        checked: 0
    },
    'he4_6': {
        name: 'he4_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 117,
        active: function() {return(Number(instrument.questions.he3.value) == 1)},
        skip: false,
        checked: 0
    },
    'he4_6_other': {
        name: 'he4_6_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 118,
        active: function() {return(Number(instrument.questions.he3.value) == 1 && Number(instrument.questions.he4_6.value) == 1)},
        skip: false
    },
    'he5_1': {
        name: 'he5_1',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 119,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he5_2': {
        name: 'he5_2',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 120,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he5_3': {
        name: 'he5_3',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 121,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he5_4': {
        name: 'he5_4',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 122,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he5_5': {
        name: 'he5_5',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 123,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he5_6': {
        name: 'he5_6',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 124,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he5_7': {
        name: 'he5_7',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 125,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he5_8': {
        name: 'he5_8',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 126,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he5_8_other': {
        name: 'he5_8_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 127,
        active: function() {return(Number(instrument.questions.he5_8.value) == 1)},
        skip: false
    },
    'he5_9': {
        name: 'he5_9',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 128,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'he6': {
        name: 'he6',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 129,
        active: function() {return(true)},
        skip: false
    },
    'he7': {
        name: 'he7',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 130,
        active: function() {return(true)},
        skip: false
    },
    'he8': {
        name: 'he8',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 131,
        active: function() {return(Number(instrument.questions.he6.value) == 1 || Number(instrument.questions.he7.value) == 1)},
        skip: false
    },
    'he9': {
        name: 'he9',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 132,
        active: function() {return(true)},
        skip: false
    },
    'he10': {
        name: 'he10',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 133,
        active: function() {return(true)},
        skip: false
    },
    'heat22': {
        name: 'heat22',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 134,
        active: function() {return(true)},
        skip: false
    },
    'heat23_1': {
        name: 'heat23_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 135,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_2': {
        name: 'heat23_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 136,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_3': {
        name: 'heat23_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 137,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_4': {
        name: 'heat23_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 138,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_5': {
        name: 'heat23_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 139,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_6': {
        name: 'heat23_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 140,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_7': {
        name: 'heat23_7',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 141,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_8': {
        name: 'heat23_8',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 142,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_9': {
        name: 'heat23_9',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 143,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_10': {
        name: 'heat23_10',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 144,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_11': {
        name: 'heat23_11',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 145,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_12': {
        name: 'heat23_12',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 146,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_13': {
        name: 'heat23_13',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 147,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_14': {
        name: 'heat23_14',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 148,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_15': {
        name: 'heat23_15',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 149,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_16': {
        name: 'heat23_16',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 150,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat23_16_other': {
        name: 'heat23_16_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 151,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_16.value) == 1)},
        skip: false
    },
    'heat24_1': {
        name: 'heat24_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 152,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_1.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_2': {
        name: 'heat24_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 153,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_2.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_3': {
        name: 'heat24_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 154,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_3.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_4': {
        name: 'heat24_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 155,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_4.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_5': {
        name: 'heat24_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 156,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_5.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_6': {
        name: 'heat24_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 157,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_6.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_7': {
        name: 'heat24_7',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 158,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_7.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_8': {
        name: 'heat24_8',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 159,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_8.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_9': {
        name: 'heat24_9',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 160,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_9.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_10': {
        name: 'heat24_10',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 161,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_10.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_11': {
        name: 'heat24_11',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 162,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_11.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_12': {
        name: 'heat24_12',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 163,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_12.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_13': {
        name: 'heat24_13',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 164,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_13.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_14': {
        name: 'heat24_14',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 165,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_14.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_15': {
        name: 'heat24_15',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 166,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_15.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_16': {
        name: 'heat24_16',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 167,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_16.value) == 1)},
        skip: false,
        checked: 0
    },
    'heat24_16_other': {
        name: 'heat24_16_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 168,
        active: function() {return(Number(instrument.questions.heat22.value) == 1 && Number(instrument.questions.heat23_16.value) == 1 && Number(instrument.questions.heat24_16.value) == 1)},
        skip: false
    },
    'heat25': {
        name: 'heat25',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 169,
        active: function() {return(Number(instrument.questions.heat22.value) == 1)},
        skip: false
    },
    'he11': {
        name: 'he11',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 170,
        active: function() {return(true)},
        skip: false
    },
    'he12_1': {
        name: 'he12_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 171,
        active: function() {return(Number(instrument.questions.he11.value) == 1)},
        skip: false,
        checked: 0
    },
    'he12_2': {
        name: 'he12_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 172,
        active: function() {return(Number(instrument.questions.he11.value) == 1)},
        skip: false,
        checked: 0
    },
    'he12_3': {
        name: 'he12_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 173,
        active: function() {return(Number(instrument.questions.he11.value) == 1)},
        skip: false,
        checked: 0
    },
    'he12_4': {
        name: 'he12_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 174,
        active: function() {return(Number(instrument.questions.he11.value) == 1)},
        skip: false,
        checked: 0
    },
    'he12_5': {
        name: 'he12_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 175,
        active: function() {return(Number(instrument.questions.he11.value) == 1)},
        skip: false,
        checked: 0
    },
    'he12_6': {
        name: 'he12_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 176,
        active: function() {return(Number(instrument.questions.he11.value) == 1)},
        skip: false,
        checked: 0
    },
    'he12_7': {
        name: 'he12_7',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 177,
        active: function() {return(Number(instrument.questions.he11.value) == 1)},
        skip: false,
        checked: 0
    },
    'he12_7_other': {
        name: 'he12_7_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 178,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he12_7.value) == 1)},
        skip: false
    },
    'he13': {
        name: 'he13',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 179,
        active: function() {return(Number(instrument.questions.he11.value) == 1)},
        skip: false
    },
    'he14_1': {
        name: 'he14_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 180,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he13.value) == 1)},
        skip: false,
        checked: 0
    },
    'he14_2': {
        name: 'he14_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 181,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he13.value) == 1)},
        skip: false,
        checked: 0
    },
    'he14_3': {
        name: 'he14_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 182,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he13.value) == 1)},
        skip: false,
        checked: 0
    },
    'he14_4': {
        name: 'he14_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 183,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he13.value) == 1)},
        skip: false,
        checked: 0
    },
    'he14_5': {
        name: 'he14_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 184,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he13.value) == 1)},
        skip: false,
        checked: 0
    },
    'he14_6': {
        name: 'he14_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 185,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he13.value) == 1)},
        skip: false,
        checked: 0
    },
    'he14_7': {
        name: 'he14_7',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 186,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he13.value) == 1)},
        skip: false,
        checked: 0
    },
    'he14_7_other': {
        name: 'he14_7_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 187,
        active: function() {return(Number(instrument.questions.he11.value) == 1 && Number(instrument.questions.he13.value) == 1 && Number(instrument.questions.he14_7.value) == 1)},
        skip: false
    },
    'he15': {
        name: 'he15',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 188,
        active: function() {return(true)},
        skip: false
    },
    'he16': {
        name: 'he16',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 189,
        active: function() {return(true)},
        skip: false
    },
    'he17': {
        name: 'he17',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 190,
        active: function() {return(true)},
        skip: false
    },
    'he18': {
        name: 'he18',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 191,
        active: function() {return(true)},
        skip: false
    },
    'he19': {
        name: 'he19',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 192,
        active: function() {return(Number(instrument.questions.pi2.value) == 2)},
        skip: false
    },
    'he20': {
        name: 'he20',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 193,
        active: function() {return(Number(instrument.questions.pi2.value) == 2)},
        skip: false
    },
    'he21': {
        name: 'he21',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 194,
        active: function() {return(true)},
        skip: true
    },
    'ls1': {
        name: 'ls1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 195,
        active: function() {return(true)},
        skip: false
    },
    'ls2_1': {
        name: 'ls2_1',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 196,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_2': {
        name: 'ls2_2',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 197,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_3': {
        name: 'ls2_3',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 198,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_4': {
        name: 'ls2_4',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 199,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_5': {
        name: 'ls2_5',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 200,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_6': {
        name: 'ls2_6',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 201,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_7': {
        name: 'ls2_7',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 202,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_8': {
        name: 'ls2_8',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 203,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_9': {
        name: 'ls2_9',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 204,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_10': {
        name: 'ls2_10',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 205,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls2_10_other': {
        name: 'ls2_10_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 206,
        active: function() {return(Number(instrument.questions.ls2_10.value) == 1)},
        skip: false
    },
    'ls2_11': {
        name: 'ls2_11',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 207,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'ls3': {
        name: 'ls3',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 208,
        active: function() {return(true)},
        skip: false
    },
    'ls4_1': {
        name: 'ls4_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 209,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls4_2': {
        name: 'ls4_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 210,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls4_3': {
        name: 'ls4_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 211,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls4_4': {
        name: 'ls4_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 212,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls4_5': {
        name: 'ls4_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 213,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls4_6': {
        name: 'ls4_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 214,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls4_7': {
        name: 'ls4_7',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 215,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls4_8': {
        name: 'ls4_8',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 216,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls4_8_other': {
        name: 'ls4_8_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 217,
        active: function() {return(Number(instrument.questions.ls3.value) == 1 && Number(instrument.questions.ls4_8.value) == 1)},
        skip: false
    },
    'ls5_1': {
        name: 'ls5_1',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 218,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls5_2': {
        name: 'ls5_2',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 219,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls5_3': {
        name: 'ls5_3',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 220,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls5_4': {
        name: 'ls5_4',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 221,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls5_5': {
        name: 'ls5_5',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 222,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls5_6': {
        name: 'ls5_6',
        type: 'checkbox',
        value: '0',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 223,
        active: function() {return(Number(instrument.questions.ls3.value) == 1)},
        skip: false,
        checked: 0
    },
    'ls5_6_other': {
        name: 'ls5_6_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 224,
        active: function() {return(Number(instrument.questions.ls3.value) == 1 && Number(instrument.questions.ls5_6.value) == 1)},
        skip: false
    },
    'ls6': {
        name: 'ls6',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 225,
        active: function() {return(true)},
        skip: true
    },
    'sc1_1': {
        name: 'sc1_1',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 226,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_2': {
        name: 'sc1_2',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 227,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_3': {
        name: 'sc1_3',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 228,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_4': {
        name: 'sc1_4',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 229,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_5': {
        name: 'sc1_5',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 230,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_6': {
        name: 'sc1_6',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 231,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_7': {
        name: 'sc1_7',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 232,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_8': {
        name: 'sc1_8',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 233,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_9': {
        name: 'sc1_9',
        type: 'checkbox',
        value: '0',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 234,
        active: function() {return(true)},
        skip: false,
        checked: 0
    },
    'sc1_9_other': {
        name: 'sc1_9_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 235,
        active: function() {return(Number(instrument.questions.sc1_9.value) == 1)},
        skip: false
    },
    'sc2': {
        name: 'sc2',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 236,
        active: function() {return(true)},
        skip: false
    },
    'sc3': {
        name: 'sc3',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 237,
        active: function() {return(true)},
        skip: false
    },
    'sc4': {
        name: 'sc4',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 238,
        active: function() {return(true)},
        skip: false
    },
    'sc5': {
        name: 'sc5',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 239,
        active: function() {return(true)},
        skip: false
    },
    'sc6': {
        name: 'sc6',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 240,
        active: function() {return(true)},
        skip: false
    },
    'sc7': {
        name: 'sc7',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 241,
        active: function() {return(Number(instrument.questions.sc6.value) == 1)},
        skip: false
    },
    'sc8': {
        name: 'sc8',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 242,
        active: function() {return(true)},
        skip: false
    },
    'sc9': {
        name: 'sc9',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 243,
        active: function() {return(true)},
        skip: false
    },
    'sc10': {
        name: 'sc10',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 244,
        active: function() {return(true)},
        skip: false
    },
    'sc11': {
        name: 'sc11',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 245,
        active: function() {return(true)},
        skip: true
    },
    'cr1': {
        name: 'cr1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 246,
        active: function() {return(true)},
        skip: false
    },
    'cr2': {
        name: 'cr2',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 247,
        active: function() {return(true)},
        skip: false
    },
    'cr3': {
        name: 'cr3',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 248,
        active: function() {return(true)},
        skip: false
    },
    'cr4': {
        name: 'cr4',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 249,
        active: function() {return(Number(instrument.questions.cr3.value) == 1)},
        skip: false
    },
    'cr5': {
        name: 'cr5',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 250,
        active: function() {return(Number(instrument.questions.cr3.value) == 0)},
        skip: false
    },
    'cr6': {
        name: 'cr6',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 251,
        active: function() {return(true)},
        skip: false
    },
    'cr7': {
        name: 'cr7',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 252,
        active: function() {return(Number(instrument.questions.cr6.value) == 1)},
        skip: false
    },
    'cr8': {
        name: 'cr8',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 253,
        active: function() {return(Number(instrument.questions.cr6.value) == 0)},
        skip: false
    },
    'cr9': {
        name: 'cr9',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 254,
        active: function() {return(true)},
        skip: false
    },
    'cr9_other': {
        name: 'cr9_other',
        type: 'textarea',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 255,
        active: function() {return(Number(instrument.questions.cr9.value) == 1)},
        skip: false
    },
    'cr10': {
        name: 'cr10',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 256,
        active: function() {return(true)},
        skip: false
    },
    'obs': {
        name: 'obs',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 257,
        active: function() {return(true)},
        skip: true
    },
};

export const questionsOrder: Array<string> = [
    'reg', 'dis', 'data', 'omr1', 'omr2', 'omr3', 'omr4', 'omr5', 'omr6', 'omr7', 'omr9', 'pi1', 'pi1a', 'pi1b',
    'pi1c', 'pi2', 'pi3', 'pi3a', 'pi4a_dk', 'pi4b', 'pi4c', 'pi5', 'pi6r', 'pi6d', 'pi6i', 'pi6n', 'pi6t',
    'pi7', 'pi8', 'pi9a', 'pi9c', 'pi9d', 'pi9h', 'pi9m', 'pi9i', 'pi9e', 'pi9f', 'pi9g', 'pi10', 'pi10a',
    'pi10b', 'pr1', 'pr2', 'pr3', 'pr4', 'lv1', 'lv1_other', 'lv2_1', 'lv2_2', 'lv2_3', 'lv2_4', 'lv2_5',
    'lv2_6', 'lv2_7', 'lv2_8', 'lv2_9', 'lv3', 'lv4', 'lv5', 'lv6_1', 'lv6_2', 'lv6_3', 'lv6_4', 'lv6_5',
    'lv6_6', 'lv6_6_other', 'lv6b', 'lv7', 'lv8', 'lv9', 'ee1', 'ee2', 'ee2_other', 'ee3', 'ee4_1', 'ee4_2',
    'ee4_3', 'ee4_4', 'ee4_5', 'ee4_6', 'ee4_6_other', 'ee5', 'ee5_other', 'ee6', 'ee7', 'ee8', 'ee9', 'ee10_1',
    'ee10_2', 'ee10_3', 'ee10_4', 'ee10_5', 'ee10_5_other', 'ee11_1', 'ee11_2', 'ee11_3', 'ee11_4', 'ee11_5',
    'ee11_6', 'ee11_7', 'ee11_8', 'ee11_9', 'ee11_10', 'ee11_11', 'ee11_12', 'ee11_12_other', 'ee12_dk', 'ee12',
    'ee13', 'he1', 'he2', 'he3', 'he4_1', 'he4_2', 'he4_3', 'he4_4', 'he4_5', 'he4_6', 'he4_6_other', 'he5_1',
    'he5_2', 'he5_3', 'he5_4', 'he5_5', 'he5_6', 'he5_7', 'he5_8', 'he5_8_other', 'he5_9', 'he6', 'he7', 'he8',
    'he9', 'he10', 'heat22', 'heat23_1', 'heat23_2', 'heat23_3', 'heat23_4', 'heat23_5', 'heat23_6', 'heat23_7',
    'heat23_8', 'heat23_9', 'heat23_10', 'heat23_11', 'heat23_12', 'heat23_13', 'heat23_14', 'heat23_15',
    'heat23_16', 'heat23_16_other', 'heat24_1', 'heat24_2', 'heat24_3', 'heat24_4', 'heat24_5', 'heat24_6',
    'heat24_7', 'heat24_8', 'heat24_9', 'heat24_10', 'heat24_11', 'heat24_12', 'heat24_13', 'heat24_14',
    'heat24_15', 'heat24_16', 'heat24_16_other', 'heat25', 'he11', 'he12_1', 'he12_2', 'he12_3', 'he12_4',
    'he12_5', 'he12_6', 'he12_7', 'he12_7_other', 'he13', 'he14_1', 'he14_2', 'he14_3', 'he14_4', 'he14_5',
    'he14_6', 'he14_7', 'he14_7_other', 'he15', 'he16', 'he17', 'he18', 'he19', 'he20', 'he21', 'ls1', 'ls2_1',
    'ls2_2', 'ls2_3', 'ls2_4', 'ls2_5', 'ls2_6', 'ls2_7', 'ls2_8', 'ls2_9', 'ls2_10', 'ls2_10_other', 'ls2_11',
    'ls3', 'ls4_1', 'ls4_2', 'ls4_3', 'ls4_4', 'ls4_5', 'ls4_6', 'ls4_7', 'ls4_8', 'ls4_8_other', 'ls5_1',
    'ls5_2', 'ls5_3', 'ls5_4', 'ls5_5', 'ls5_6', 'ls5_6_other', 'ls6', 'sc1_1', 'sc1_2', 'sc1_3', 'sc1_4',
    'sc1_5', 'sc1_6', 'sc1_7', 'sc1_8', 'sc1_9', 'sc1_9_other', 'sc2', 'sc3', 'sc4', 'sc5', 'sc6', 'sc7', 'sc8',
    'sc9', 'sc10', 'sc11', 'cr1', 'cr2', 'cr3', 'cr4', 'cr5', 'cr6', 'cr7', 'cr8', 'cr9', 'cr9_other', 'cr10',
    'obs'
];

export const exportHeader: Array<{ id: string; title: string }> = [
    {'id': 'reg', 'title': 'REG'},
    {'id': 'dis', 'title': 'DIS'},
    {'id': 'data', 'title': 'DATA'},
    {'id': 'omr1', 'title': 'OMR1'},
    {'id': 'omr2', 'title': 'OMR2'},
    {'id': 'omr3', 'title': 'OMR3'},
    {'id': 'omr4', 'title': 'OMR4'},
    {'id': 'omr5', 'title': 'OMR5'},
    {'id': 'omr6', 'title': 'OMR6'},
    {'id': 'omr7', 'title': 'OMR7'},
    {'id': 'omr9', 'title': 'OMR9'},
    {'id': 'pi1', 'title': 'PI1'},
    {'id': 'pi1a', 'title': 'PI1A'},
    {'id': 'pi1b', 'title': 'PI1B'},
    {'id': 'pi1c', 'title': 'PI1C'},
    {'id': 'pi2', 'title': 'PI2'},
    {'id': 'pi3', 'title': 'PI3'},
    {'id': 'pi3a', 'title': 'PI3A'},
    {'id': 'pi4a_dk', 'title': 'PI4A_DK'},
    {'id': 'pi4b', 'title': 'PI4B'},
    {'id': 'pi4c', 'title': 'PI4C'},
    {'id': 'pi5', 'title': 'PI5'},
    {'id': 'pi6r', 'title': 'PI6R'},
    {'id': 'pi6d', 'title': 'PI6D'},
    {'id': 'pi6i', 'title': 'PI6I'},
    {'id': 'pi6n', 'title': 'PI6N'},
    {'id': 'pi6t', 'title': 'PI6T'},
    {'id': 'pi7', 'title': 'PI7'},
    {'id': 'pi8', 'title': 'PI8'},
    {'id': 'pi9a', 'title': 'PI9A'},
    {'id': 'pi9c', 'title': 'PI9C'},
    {'id': 'pi9d', 'title': 'PI9D'},
    {'id': 'pi9h', 'title': 'PI9H'},
    {'id': 'pi9m', 'title': 'PI9M'},
    {'id': 'pi9i', 'title': 'PI9I'},
    {'id': 'pi9e', 'title': 'PI9E'},
    {'id': 'pi9f', 'title': 'PI9F'},
    {'id': 'pi9g', 'title': 'PI9G'},
    {'id': 'pi10', 'title': 'PI10'},
    {'id': 'pi10a', 'title': 'PI10A'},
    {'id': 'pi10b', 'title': 'PI10B'},
    {'id': 'pr1', 'title': 'PR1'},
    {'id': 'pr2', 'title': 'PR2'},
    {'id': 'pr3', 'title': 'PR3'},
    {'id': 'pr4', 'title': 'PR4'},
    {'id': 'lv1', 'title': 'LV1'},
    {'id': 'lv1_other', 'title': 'LV1_OTHER'},
    {'id': 'lv2_1', 'title': 'LV2_1'},
    {'id': 'lv2_2', 'title': 'LV2_2'},
    {'id': 'lv2_3', 'title': 'LV2_3'},
    {'id': 'lv2_4', 'title': 'LV2_4'},
    {'id': 'lv2_5', 'title': 'LV2_5'},
    {'id': 'lv2_6', 'title': 'LV2_6'},
    {'id': 'lv2_7', 'title': 'LV2_7'},
    {'id': 'lv2_8', 'title': 'LV2_8'},
    {'id': 'lv2_9', 'title': 'LV2_9'},
    {'id': 'lv3', 'title': 'LV3'},
    {'id': 'lv4', 'title': 'LV4'},
    {'id': 'lv5', 'title': 'LV5'},
    {'id': 'lv6_1', 'title': 'LV6_1'},
    {'id': 'lv6_2', 'title': 'LV6_2'},
    {'id': 'lv6_3', 'title': 'LV6_3'},
    {'id': 'lv6_4', 'title': 'LV6_4'},
    {'id': 'lv6_5', 'title': 'LV6_5'},
    {'id': 'lv6_6', 'title': 'LV6_6'},
    {'id': 'lv6_6_other', 'title': 'LV6_6_OTHER'},
    {'id': 'lv6b', 'title': 'LV6B'},
    {'id': 'lv7', 'title': 'LV7'},
    {'id': 'lv8', 'title': 'LV8'},
    {'id': 'lv9', 'title': 'LV9'},
    {'id': 'ee1', 'title': 'EE1'},
    {'id': 'ee2', 'title': 'EE2'},
    {'id': 'ee2_other', 'title': 'EE2_OTHER'},
    {'id': 'ee3', 'title': 'EE3'},
    {'id': 'ee4_1', 'title': 'EE4_1'},
    {'id': 'ee4_2', 'title': 'EE4_2'},
    {'id': 'ee4_3', 'title': 'EE4_3'},
    {'id': 'ee4_4', 'title': 'EE4_4'},
    {'id': 'ee4_5', 'title': 'EE4_5'},
    {'id': 'ee4_6', 'title': 'EE4_6'},
    {'id': 'ee4_6_other', 'title': 'EE4_6_OTHER'},
    {'id': 'ee5', 'title': 'EE5'},
    {'id': 'ee5_other', 'title': 'EE5_OTHER'},
    {'id': 'ee6', 'title': 'EE6'},
    {'id': 'ee7', 'title': 'EE7'},
    {'id': 'ee8', 'title': 'EE8'},
    {'id': 'ee9', 'title': 'EE9'},
    {'id': 'ee10_1', 'title': 'EE10_1'},
    {'id': 'ee10_2', 'title': 'EE10_2'},
    {'id': 'ee10_3', 'title': 'EE10_3'},
    {'id': 'ee10_4', 'title': 'EE10_4'},
    {'id': 'ee10_5', 'title': 'EE10_5'},
    {'id': 'ee10_5_other', 'title': 'EE10_5_OTHER'},
    {'id': 'ee11_1', 'title': 'EE11_1'},
    {'id': 'ee11_2', 'title': 'EE11_2'},
    {'id': 'ee11_3', 'title': 'EE11_3'},
    {'id': 'ee11_4', 'title': 'EE11_4'},
    {'id': 'ee11_5', 'title': 'EE11_5'},
    {'id': 'ee11_6', 'title': 'EE11_6'},
    {'id': 'ee11_7', 'title': 'EE11_7'},
    {'id': 'ee11_8', 'title': 'EE11_8'},
    {'id': 'ee11_9', 'title': 'EE11_9'},
    {'id': 'ee11_10', 'title': 'EE11_10'},
    {'id': 'ee11_11', 'title': 'EE11_11'},
    {'id': 'ee11_12', 'title': 'EE11_12'},
    {'id': 'ee11_12_other', 'title': 'EE11_12_OTHER'},
    {'id': 'ee12_dk', 'title': 'EE12_DK'},
    {'id': 'ee12', 'title': 'EE12'},
    {'id': 'ee13', 'title': 'EE13'},
    {'id': 'he1', 'title': 'HE1'},
    {'id': 'he2', 'title': 'HE2'},
    {'id': 'he3', 'title': 'HE3'},
    {'id': 'he4_1', 'title': 'HE4_1'},
    {'id': 'he4_2', 'title': 'HE4_2'},
    {'id': 'he4_3', 'title': 'HE4_3'},
    {'id': 'he4_4', 'title': 'HE4_4'},
    {'id': 'he4_5', 'title': 'HE4_5'},
    {'id': 'he4_6', 'title': 'HE4_6'},
    {'id': 'he4_6_other', 'title': 'HE4_6_OTHER'},
    {'id': 'he5_1', 'title': 'HE5_1'},
    {'id': 'he5_2', 'title': 'HE5_2'},
    {'id': 'he5_3', 'title': 'HE5_3'},
    {'id': 'he5_4', 'title': 'HE5_4'},
    {'id': 'he5_5', 'title': 'HE5_5'},
    {'id': 'he5_6', 'title': 'HE5_6'},
    {'id': 'he5_7', 'title': 'HE5_7'},
    {'id': 'he5_8', 'title': 'HE5_8'},
    {'id': 'he5_8_other', 'title': 'HE5_8_OTHER'},
    {'id': 'he5_9', 'title': 'HE5_9'},
    {'id': 'he6', 'title': 'HE6'},
    {'id': 'he7', 'title': 'HE7'},
    {'id': 'he8', 'title': 'HE8'},
    {'id': 'he9', 'title': 'HE9'},
    {'id': 'he10', 'title': 'HE10'},
    {'id': 'heat22', 'title': 'HEAT22'},
    {'id': 'heat23_1', 'title': 'HEAT23_1'},
    {'id': 'heat23_2', 'title': 'HEAT23_2'},
    {'id': 'heat23_3', 'title': 'HEAT23_3'},
    {'id': 'heat23_4', 'title': 'HEAT23_4'},
    {'id': 'heat23_5', 'title': 'HEAT23_5'},
    {'id': 'heat23_6', 'title': 'HEAT23_6'},
    {'id': 'heat23_7', 'title': 'HEAT23_7'},
    {'id': 'heat23_8', 'title': 'HEAT23_8'},
    {'id': 'heat23_9', 'title': 'HEAT23_9'},
    {'id': 'heat23_10', 'title': 'HEAT23_10'},
    {'id': 'heat23_11', 'title': 'HEAT23_11'},
    {'id': 'heat23_12', 'title': 'HEAT23_12'},
    {'id': 'heat23_13', 'title': 'HEAT23_13'},
    {'id': 'heat23_14', 'title': 'HEAT23_14'},
    {'id': 'heat23_15', 'title': 'HEAT23_15'},
    {'id': 'heat23_16', 'title': 'HEAT23_16'},
    {'id': 'heat23_16_other', 'title': 'HEAT23_16_OTHER'},
    {'id': 'heat24_1', 'title': 'HEAT24_1'},
    {'id': 'heat24_2', 'title': 'HEAT24_2'},
    {'id': 'heat24_3', 'title': 'HEAT24_3'},
    {'id': 'heat24_4', 'title': 'HEAT24_4'},
    {'id': 'heat24_5', 'title': 'HEAT24_5'},
    {'id': 'heat24_6', 'title': 'HEAT24_6'},
    {'id': 'heat24_7', 'title': 'HEAT24_7'},
    {'id': 'heat24_8', 'title': 'HEAT24_8'},
    {'id': 'heat24_9', 'title': 'HEAT24_9'},
    {'id': 'heat24_10', 'title': 'HEAT24_10'},
    {'id': 'heat24_11', 'title': 'HEAT24_11'},
    {'id': 'heat24_12', 'title': 'HEAT24_12'},
    {'id': 'heat24_13', 'title': 'HEAT24_13'},
    {'id': 'heat24_14', 'title': 'HEAT24_14'},
    {'id': 'heat24_15', 'title': 'HEAT24_15'},
    {'id': 'heat24_16', 'title': 'HEAT24_16'},
    {'id': 'heat24_16_other', 'title': 'HEAT24_16_OTHER'},
    {'id': 'heat25', 'title': 'HEAT25'},
    {'id': 'he11', 'title': 'HE11'},
    {'id': 'he12_1', 'title': 'HE12_1'},
    {'id': 'he12_2', 'title': 'HE12_2'},
    {'id': 'he12_3', 'title': 'HE12_3'},
    {'id': 'he12_4', 'title': 'HE12_4'},
    {'id': 'he12_5', 'title': 'HE12_5'},
    {'id': 'he12_6', 'title': 'HE12_6'},
    {'id': 'he12_7', 'title': 'HE12_7'},
    {'id': 'he12_7_other', 'title': 'HE12_7_OTHER'},
    {'id': 'he13', 'title': 'HE13'},
    {'id': 'he14_1', 'title': 'HE14_1'},
    {'id': 'he14_2', 'title': 'HE14_2'},
    {'id': 'he14_3', 'title': 'HE14_3'},
    {'id': 'he14_4', 'title': 'HE14_4'},
    {'id': 'he14_5', 'title': 'HE14_5'},
    {'id': 'he14_6', 'title': 'HE14_6'},
    {'id': 'he14_7', 'title': 'HE14_7'},
    {'id': 'he14_7_other', 'title': 'HE14_7_OTHER'},
    {'id': 'he15', 'title': 'HE15'},
    {'id': 'he16', 'title': 'HE16'},
    {'id': 'he17', 'title': 'HE17'},
    {'id': 'he18', 'title': 'HE18'},
    {'id': 'he19', 'title': 'HE19'},
    {'id': 'he20', 'title': 'HE20'},
    {'id': 'he21', 'title': 'HE21'},
    {'id': 'ls1', 'title': 'LS1'},
    {'id': 'ls2_1', 'title': 'LS2_1'},
    {'id': 'ls2_2', 'title': 'LS2_2'},
    {'id': 'ls2_3', 'title': 'LS2_3'},
    {'id': 'ls2_4', 'title': 'LS2_4'},
    {'id': 'ls2_5', 'title': 'LS2_5'},
    {'id': 'ls2_6', 'title': 'LS2_6'},
    {'id': 'ls2_7', 'title': 'LS2_7'},
    {'id': 'ls2_8', 'title': 'LS2_8'},
    {'id': 'ls2_9', 'title': 'LS2_9'},
    {'id': 'ls2_10', 'title': 'LS2_10'},
    {'id': 'ls2_10_other', 'title': 'LS2_10_OTHER'},
    {'id': 'ls2_11', 'title': 'LS2_11'},
    {'id': 'ls3', 'title': 'LS3'},
    {'id': 'ls4_1', 'title': 'LS4_1'},
    {'id': 'ls4_2', 'title': 'LS4_2'},
    {'id': 'ls4_3', 'title': 'LS4_3'},
    {'id': 'ls4_4', 'title': 'LS4_4'},
    {'id': 'ls4_5', 'title': 'LS4_5'},
    {'id': 'ls4_6', 'title': 'LS4_6'},
    {'id': 'ls4_7', 'title': 'LS4_7'},
    {'id': 'ls4_8', 'title': 'LS4_8'},
    {'id': 'ls4_8_other', 'title': 'LS4_8_OTHER'},
    {'id': 'ls5_1', 'title': 'LS5_1'},
    {'id': 'ls5_2', 'title': 'LS5_2'},
    {'id': 'ls5_3', 'title': 'LS5_3'},
    {'id': 'ls5_4', 'title': 'LS5_4'},
    {'id': 'ls5_5', 'title': 'LS5_5'},
    {'id': 'ls5_6', 'title': 'LS5_6'},
    {'id': 'ls5_6_other', 'title': 'LS5_6_OTHER'},
    {'id': 'ls6', 'title': 'LS6'},
    {'id': 'sc1_1', 'title': 'SC1_1'},
    {'id': 'sc1_2', 'title': 'SC1_2'},
    {'id': 'sc1_3', 'title': 'SC1_3'},
    {'id': 'sc1_4', 'title': 'SC1_4'},
    {'id': 'sc1_5', 'title': 'SC1_5'},
    {'id': 'sc1_6', 'title': 'SC1_6'},
    {'id': 'sc1_7', 'title': 'SC1_7'},
    {'id': 'sc1_8', 'title': 'SC1_8'},
    {'id': 'sc1_9', 'title': 'SC1_9'},
    {'id': 'sc1_9_other', 'title': 'SC1_9_OTHER'},
    {'id': 'sc2', 'title': 'SC2'},
    {'id': 'sc3', 'title': 'SC3'},
    {'id': 'sc4', 'title': 'SC4'},
    {'id': 'sc5', 'title': 'SC5'},
    {'id': 'sc6', 'title': 'SC6'},
    {'id': 'sc7', 'title': 'SC7'},
    {'id': 'sc8', 'title': 'SC8'},
    {'id': 'sc9', 'title': 'SC9'},
    {'id': 'sc10', 'title': 'SC10'},
    {'id': 'sc11', 'title': 'SC11'},
    {'id': 'cr1', 'title': 'CR1'},
    {'id': 'cr2', 'title': 'CR2'},
    {'id': 'cr3', 'title': 'CR3'},
    {'id': 'cr4', 'title': 'CR4'},
    {'id': 'cr5', 'title': 'CR5'},
    {'id': 'cr6', 'title': 'CR6'},
    {'id': 'cr7', 'title': 'CR7'},
    {'id': 'cr8', 'title': 'CR8'},
    {'id': 'cr9', 'title': 'CR9'},
    {'id': 'cr9_other', 'title': 'CR9_OTHER'},
    {'id': 'cr10', 'title': 'CR10'},
    {'id': 'obs', 'title': 'OBS'},
];