import instrument from '../../libraries/instrument';
import { QuestionObjectType } from '../../libraries/interfaces';

export const questions: QuestionObjectType = {
    'q1': {
        name: 'q1',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: true,
        readonly: true,
        order: 0,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'q2': {
        name: 'q2',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 1,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'q3': {
        name: 'q3',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 2,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'q4': {
        name: 'q4',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 3,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'q5': {
        name: 'q5',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 4,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'q6': {
        name: 'q6',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 5,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i1': {
        name: 'i1',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 6,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i2': {
        name: 'i2',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 7,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i3': {
        name: 'i3',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 8,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i4': {
        name: 'i4',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 9,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i4a': {
        name: 'i4a',
        type: 'select',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 10,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i4b': {
        name: 'i4b',
        type: 'select',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 11,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i4c': {
        name: 'i4c',
        type: 'select',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 12,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i4d': {
        name: 'i4d',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: true,
        readonly: true,
        order: 13,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'i9': {
        name: 'i9',
        type: 'select',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 14,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'tnr0': {
        name: 'tnr0',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 15,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'net1': {
        name: 'net1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 16,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'net1a_b': {
        name: 'net1a_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 17,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1a_g': {
        name: 'net1a_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 18,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1a_t': {
        name: 'net1a_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 19,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1b_b': {
        name: 'net1b_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 20,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1b_g': {
        name: 'net1b_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 21,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1b_t': {
        name: 'net1b_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 22,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1c_b': {
        name: 'net1c_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 23,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1c_g': {
        name: 'net1c_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 24,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1c_t': {
        name: 'net1c_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 25,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1d_b': {
        name: 'net1d_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 26,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1d_g': {
        name: 'net1d_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 27,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1d_t': {
        name: 'net1d_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 28,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1e_b': {
        name: 'net1e_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 29,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1e_g': {
        name: 'net1e_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 30,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'net1e_t': {
        name: 'net1e_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 31,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'tnet_b': {
        name: 'tnet_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 32,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'tnet_g': {
        name: 'tnet_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 33,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'tnet_t': {
        name: 'tnet_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 34,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes1_b': {
        name: 'nes1_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 35,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes1_g': {
        name: 'nes1_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 36,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes1_t': {
        name: 'nes1_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 37,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes2_b': {
        name: 'nes2_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 38,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes2_g': {
        name: 'nes2_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 39,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes2_t': {
        name: 'nes2_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 40,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes3_b': {
        name: 'nes3_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 41,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes3_g': {
        name: 'nes3_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 42,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nes3_t': {
        name: 'nes3_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 43,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nest_b': {
        name: 'nest_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 44,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nest_g': {
        name: 'nest_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 45,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nest_t': {
        name: 'nest_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 46,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo1_b': {
        name: 'neo1_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 47,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo1_g': {
        name: 'neo1_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 48,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo1_t': {
        name: 'neo1_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 49,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo2_b': {
        name: 'neo2_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 50,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo2_g': {
        name: 'neo2_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 51,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo2_t': {
        name: 'neo2_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 52,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo3_b': {
        name: 'neo3_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 53,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo3_g': {
        name: 'neo3_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 54,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo3_t': {
        name: 'neo3_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 55,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo4_b': {
        name: 'neo4_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 56,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo4_g': {
        name: 'neo4_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 57,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo4_t': {
        name: 'neo4_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 58,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo5_b': {
        name: 'neo5_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 59,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo5_g': {
        name: 'neo5_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 60,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo5_t': {
        name: 'neo5_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 61,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo6_b': {
        name: 'neo6_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 62,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo6_g': {
        name: 'neo6_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 63,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo6_t': {
        name: 'neo6_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 64,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo7_b': {
        name: 'neo7_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 65,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo7_g': {
        name: 'neo7_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 66,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo7_t': {
        name: 'neo7_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 67,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo8_b': {
        name: 'neo8_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 68,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo8_g': {
        name: 'neo8_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 69,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo8_t': {
        name: 'neo8_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 70,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo_b': {
        name: 'neo_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 71,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo_g': {
        name: 'neo_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 72,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'neo_t': {
        name: 'neo_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 73,
        active: function () { return (Number(instrument.questions.net1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1': {
        name: 'nex1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 74,
        active: function () { return (true) },
        error: '',
        skip: false
    },
    'nex1a_b': {
        name: 'nex1a_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 75,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1a_g': {
        name: 'nex1a_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 76,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1a_t': {
        name: 'nex1a_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 77,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1b_b': {
        name: 'nex1b_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 78,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1b_g': {
        name: 'nex1b_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 79,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1b_t': {
        name: 'nex1b_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 80,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1c_b': {
        name: 'nex1c_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 81,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1c_g': {
        name: 'nex1c_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 82,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1c_t': {
        name: 'nex1c_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 83,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1d_b': {
        name: 'nex1d_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 84,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1d_g': {
        name: 'nex1d_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 85,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1d_t': {
        name: 'nex1d_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 86,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1e_b': {
        name: 'nex1e_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 87,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1e_g': {
        name: 'nex1e_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 88,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1e_t': {
        name: 'nex1e_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 89,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1f_b': {
        name: 'nex1f_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 90,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1f_g': {
        name: 'nex1f_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 91,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'nex1f_t': {
        name: 'nex1f_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 92,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'next_b': {
        name: 'next_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 93,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'next_g': {
        name: 'next_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 94,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'next_t': {
        name: 'next_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 95,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos1_b': {
        name: 'eos1_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 96,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos1_g': {
        name: 'eos1_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 97,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos1_t': {
        name: 'eos1_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 98,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos2_b': {
        name: 'eos2_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 99,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos2_g': {
        name: 'eos2_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 100,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos2_t': {
        name: 'eos2_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 101,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos3_b': {
        name: 'eos3_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 102,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos3_g': {
        name: 'eos3_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 103,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos3_t': {
        name: 'eos3_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 104,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eos4_b': {
        name: 'eos4_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 105,
        active: function () { return (Number(instrument.questions.nex1.value) == 1 && (Number(instrument.questions.i9.value) == 21 || Number(instrument.questions.i9.value) == 22 || Number(instrument.questions.i9.value) == 23 || Number(instrument.questions.i9.value) == 24 || Number(instrument.questions.i9.value) == 25 || Number(instrument.questions.i9.value) == 26)) },
        error: '',
        skip: false
    },
    'eos4_g': {
        name: 'eos4_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 106,
        active: function () { return (Number(instrument.questions.nex1.value) == 1 && (Number(instrument.questions.i9.value) == 21 || Number(instrument.questions.i9.value) == 22 || Number(instrument.questions.i9.value) == 23 || Number(instrument.questions.i9.value) == 24 || Number(instrument.questions.i9.value) == 25 || Number(instrument.questions.i9.value) == 26)) },
        error: '',
        skip: false
    },
    'eos4_t': {
        name: 'eos4_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 107,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eost_b': {
        name: 'eost_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 108,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eost_g': {
        name: 'eost_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 109,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'eost_t': {
        name: 'eost_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 110,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext0_b': {
        name: 'ext0_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 111,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext0_g': {
        name: 'ext0_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 112,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext0_t': {
        name: 'ext0_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 113,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext1_b': {
        name: 'ext1_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 114,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext1_g': {
        name: 'ext1_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 115,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext1_t': {
        name: 'ext1_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 116,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext2_b': {
        name: 'ext2_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 117,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext2_g': {
        name: 'ext2_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 118,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext2_t': {
        name: 'ext2_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 119,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext3_b': {
        name: 'ext3_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 120,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext3_g': {
        name: 'ext3_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 121,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext3_t': {
        name: 'ext3_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 122,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext4_b': {
        name: 'ext4_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 123,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext4_g': {
        name: 'ext4_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 124,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext4_t': {
        name: 'ext4_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 125,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext5_b': {
        name: 'ext5_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 126,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext5_g': {
        name: 'ext5_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 127,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext5_t': {
        name: 'ext5_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 128,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext6_b': {
        name: 'ext6_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 129,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext6_g': {
        name: 'ext6_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 130,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext6_t': {
        name: 'ext6_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 131,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext7_b': {
        name: 'ext7_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 132,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext7_g': {
        name: 'ext7_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 133,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'ext7_t': {
        name: 'ext7_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 134,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'extt_b': {
        name: 'extt_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 135,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'extt_g': {
        name: 'extt_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 136,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'extt_t': {
        name: 'extt_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 137,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa1_b': {
        name: 'tsa1_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 138,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa1_g': {
        name: 'tsa1_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 139,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa1_t': {
        name: 'tsa1_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 140,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa2_b': {
        name: 'tsa2_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 141,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa2_g': {
        name: 'tsa2_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 142,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa2_t': {
        name: 'tsa2_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 143,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa3_b': {
        name: 'tsa3_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 144,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa3_g': {
        name: 'tsa3_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 145,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tsa3_t': {
        name: 'tsa3_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 146,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tnr1_b': {
        name: 'tnr1_b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 147,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tnr1_g': {
        name: 'tnr1_g',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 148,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
    'tnr1_t': {
        name: 'tnr1_t',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 149,
        active: function () { return (Number(instrument.questions.nex1.value) == 1) },
        error: '',
        skip: false
    },
};

export const questionOrder: Array<string> = [
    'q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'i1', 'i2', 'i3', 'i4', 'i4a', 'i4b', 'i4c', 'i4d', 'i9', 'tnr0', 'net1',
    'net1a_b', 'net1a_g', 'net1a_t', 'net1b_b', 'net1b_g', 'net1b_t', 'net1c_b', 'net1c_g', 'net1c_t', 'net1d_b',
    'net1d_g', 'net1d_t', 'net1e_b', 'net1e_g', 'net1e_t', 'tnet_b', 'tnet_g', 'tnet_t', 'nes1_b', 'nes1_g',
    'nes1_t', 'nes2_b', 'nes2_g', 'nes2_t', 'nes3_b', 'nes3_g', 'nes3_t', 'nest_b', 'nest_g', 'nest_t', 'neo1_b',
    'neo1_g', 'neo1_t', 'neo2_b', 'neo2_g', 'neo2_t', 'neo3_b', 'neo3_g', 'neo3_t', 'neo4_b', 'neo4_g', 'neo4_t',
    'neo5_b', 'neo5_g', 'neo5_t', 'neo6_b', 'neo6_g', 'neo6_t', 'neo7_b', 'neo7_g', 'neo7_t', 'neo8_b', 'neo8_g',
    'neo8_t', 'neo_b', 'neo_g', 'neo_t', 'nex1', 'nex1a_b', 'nex1a_g', 'nex1a_t', 'nex1b_b', 'nex1b_g',
    'nex1b_t', 'nex1c_b', 'nex1c_g', 'nex1c_t', 'nex1d_b', 'nex1d_g', 'nex1d_t', 'nex1e_b', 'nex1e_g', 'nex1e_t',
    'nex1f_b', 'nex1f_g', 'nex1f_t', 'next_b', 'next_g', 'next_t', 'eos1_b', 'eos1_g', 'eos1_t', 'eos2_b',
    'eos2_g', 'eos2_t', 'eos3_b', 'eos3_g', 'eos3_t', 'eos4_b', 'eos4_g', 'eos4_t', 'eost_b', 'eost_g', 'eost_t',
    'ext0_b', 'ext0_g', 'ext0_t', 'ext1_b', 'ext1_g', 'ext1_t', 'ext2_b', 'ext2_g', 'ext2_t', 'ext3_b', 'ext3_g',
    'ext3_t', 'ext4_b', 'ext4_g', 'ext4_t', 'ext5_b', 'ext5_g', 'ext5_t', 'ext6_b', 'ext6_g', 'ext6_t', 'ext7_b',
    'ext7_g', 'ext7_t', 'extt_b', 'extt_g', 'extt_t', 'tsa1_b', 'tsa1_g', 'tsa1_t', 'tsa2_b', 'tsa2_g', 'tsa2_t',
    'tsa3_b', 'tsa3_g', 'tsa3_t', 'tnr1_b', 'tnr1_g', 'tnr1_t'
];

export const exportHeader: Array<{ id: string; title: string }> = [
    { 'id': 'q1', 'title': 'Q1' },
    { 'id': 'q2', 'title': 'Q2' },
    { 'id': 'q3', 'title': 'Q3' },
    { 'id': 'q4', 'title': 'Q4' },
    { 'id': 'q5', 'title': 'Q5' },
    { 'id': 'q6', 'title': 'Q6' },
    { 'id': 'i1', 'title': 'I1' },
    { 'id': 'i2', 'title': 'I2' },
    { 'id': 'i3', 'title': 'I3' },
    { 'id': 'i4', 'title': 'I4' },
    { 'id': 'i4a', 'title': 'I4A' },
    { 'id': 'i4b', 'title': 'I4B' },
    { 'id': 'i4c', 'title': 'I4C' },
    { 'id': 'i4d', 'title': 'I4D' },
    { 'id': 'i9', 'title': 'I9' },
    { 'id': 'tnr0', 'title': 'TNR0' },
    { 'id': 'net1', 'title': 'NET1' },
    { 'id': 'net1a_b', 'title': 'NET1A_B' },
    { 'id': 'net1a_g', 'title': 'NET1A_G' },
    { 'id': 'net1a_t', 'title': 'NET1A_T' },
    { 'id': 'net1b_b', 'title': 'NET1B_B' },
    { 'id': 'net1b_g', 'title': 'NET1B_G' },
    { 'id': 'net1b_t', 'title': 'NET1B_T' },
    { 'id': 'net1c_b', 'title': 'NET1C_B' },
    { 'id': 'net1c_g', 'title': 'NET1C_G' },
    { 'id': 'net1c_t', 'title': 'NET1C_T' },
    { 'id': 'net1d_b', 'title': 'NET1D_B' },
    { 'id': 'net1d_g', 'title': 'NET1D_G' },
    { 'id': 'net1d_t', 'title': 'NET1D_T' },
    { 'id': 'net1e_b', 'title': 'NET1E_B' },
    { 'id': 'net1e_g', 'title': 'NET1E_G' },
    { 'id': 'net1e_t', 'title': 'NET1E_T' },
    { 'id': 'tnet_b', 'title': 'TNET_B' },
    { 'id': 'tnet_g', 'title': 'TNET_G' },
    { 'id': 'tnet_t', 'title': 'TNET_T' },
    { 'id': 'nes1_b', 'title': 'NES1_B' },
    { 'id': 'nes1_g', 'title': 'NES1_G' },
    { 'id': 'nes1_t', 'title': 'NES1_T' },
    { 'id': 'nes2_b', 'title': 'NES2_B' },
    { 'id': 'nes2_g', 'title': 'NES2_G' },
    { 'id': 'nes2_t', 'title': 'NES2_T' },
    { 'id': 'nes3_b', 'title': 'NES3_B' },
    { 'id': 'nes3_g', 'title': 'NES3_G' },
    { 'id': 'nes3_t', 'title': 'NES3_T' },
    { 'id': 'nest_b', 'title': 'NEST_B' },
    { 'id': 'nest_g', 'title': 'NEST_G' },
    { 'id': 'nest_t', 'title': 'NEST_T' },
    { 'id': 'neo1_b', 'title': 'NEO1_B' },
    { 'id': 'neo1_g', 'title': 'NEO1_G' },
    { 'id': 'neo1_t', 'title': 'NEO1_T' },
    { 'id': 'neo2_b', 'title': 'NEO2_B' },
    { 'id': 'neo2_g', 'title': 'NEO2_G' },
    { 'id': 'neo2_t', 'title': 'NEO2_T' },
    { 'id': 'neo3_b', 'title': 'NEO3_B' },
    { 'id': 'neo3_g', 'title': 'NEO3_G' },
    { 'id': 'neo3_t', 'title': 'NEO3_T' },
    { 'id': 'neo4_b', 'title': 'NEO4_B' },
    { 'id': 'neo4_g', 'title': 'NEO4_G' },
    { 'id': 'neo4_t', 'title': 'NEO4_T' },
    { 'id': 'neo5_b', 'title': 'NEO5_B' },
    { 'id': 'neo5_g', 'title': 'NEO5_G' },
    { 'id': 'neo5_t', 'title': 'NEO5_T' },
    { 'id': 'neo6_b', 'title': 'NEO6_B' },
    { 'id': 'neo6_g', 'title': 'NEO6_G' },
    { 'id': 'neo6_t', 'title': 'NEO6_T' },
    { 'id': 'neo7_b', 'title': 'NEO7_B' },
    { 'id': 'neo7_g', 'title': 'NEO7_G' },
    { 'id': 'neo7_t', 'title': 'NEO7_T' },
    { 'id': 'neo8_b', 'title': 'NEO8_B' },
    { 'id': 'neo8_g', 'title': 'NEO8_G' },
    { 'id': 'neo8_t', 'title': 'NEO8_T' },
    { 'id': 'neo_b', 'title': 'NEO_B' },
    { 'id': 'neo_g', 'title': 'NEO_G' },
    { 'id': 'neo_t', 'title': 'NEO_T' },
    { 'id': 'nex1', 'title': 'NEX1' },
    { 'id': 'nex1a_b', 'title': 'NEX1A_B' },
    { 'id': 'nex1a_g', 'title': 'NEX1A_G' },
    { 'id': 'nex1a_t', 'title': 'NEX1A_T' },
    { 'id': 'nex1b_b', 'title': 'NEX1B_B' },
    { 'id': 'nex1b_g', 'title': 'NEX1B_G' },
    { 'id': 'nex1b_t', 'title': 'NEX1B_T' },
    { 'id': 'nex1c_b', 'title': 'NEX1C_B' },
    { 'id': 'nex1c_g', 'title': 'NEX1C_G' },
    { 'id': 'nex1c_t', 'title': 'NEX1C_T' },
    { 'id': 'nex1d_b', 'title': 'NEX1D_B' },
    { 'id': 'nex1d_g', 'title': 'NEX1D_G' },
    { 'id': 'nex1d_t', 'title': 'NEX1D_T' },
    { 'id': 'nex1e_b', 'title': 'NEX1E_B' },
    { 'id': 'nex1e_g', 'title': 'NEX1E_G' },
    { 'id': 'nex1e_t', 'title': 'NEX1E_T' },
    { 'id': 'nex1f_b', 'title': 'NEX1F_B' },
    { 'id': 'nex1f_g', 'title': 'NEX1F_G' },
    { 'id': 'nex1f_t', 'title': 'NEX1F_T' },
    { 'id': 'next_b', 'title': 'NEXT_B' },
    { 'id': 'next_g', 'title': 'NEXT_G' },
    { 'id': 'next_t', 'title': 'NEXT_T' },
    { 'id': 'eos1_b', 'title': 'EOS1_B' },
    { 'id': 'eos1_g', 'title': 'EOS1_G' },
    { 'id': 'eos1_t', 'title': 'EOS1_T' },
    { 'id': 'eos2_b', 'title': 'EOS2_B' },
    { 'id': 'eos2_g', 'title': 'EOS2_G' },
    { 'id': 'eos2_t', 'title': 'EOS2_T' },
    { 'id': 'eos3_b', 'title': 'EOS3_B' },
    { 'id': 'eos3_g', 'title': 'EOS3_G' },
    { 'id': 'eos3_t', 'title': 'EOS3_T' },
    { 'id': 'eos4_b', 'title': 'EOS4_B' },
    { 'id': 'eos4_g', 'title': 'EOS4_G' },
    { 'id': 'eos4_t', 'title': 'EOS4_T' },
    { 'id': 'eost_b', 'title': 'EOST_B' },
    { 'id': 'eost_g', 'title': 'EOST_G' },
    { 'id': 'eost_t', 'title': 'EOST_T' },
    { 'id': 'ext0_b', 'title': 'EXT0_B' },
    { 'id': 'ext0_g', 'title': 'EXT0_G' },
    { 'id': 'ext0_t', 'title': 'EXT0_T' },
    { 'id': 'ext1_b', 'title': 'EXT1_B' },
    { 'id': 'ext1_g', 'title': 'EXT1_G' },
    { 'id': 'ext1_t', 'title': 'EXT1_T' },
    { 'id': 'ext2_b', 'title': 'EXT2_B' },
    { 'id': 'ext2_g', 'title': 'EXT2_G' },
    { 'id': 'ext2_t', 'title': 'EXT2_T' },
    { 'id': 'ext3_b', 'title': 'EXT3_B' },
    { 'id': 'ext3_g', 'title': 'EXT3_G' },
    { 'id': 'ext3_t', 'title': 'EXT3_T' },
    { 'id': 'ext4_b', 'title': 'EXT4_B' },
    { 'id': 'ext4_g', 'title': 'EXT4_G' },
    { 'id': 'ext4_t', 'title': 'EXT4_T' },
    { 'id': 'ext5_b', 'title': 'EXT5_B' },
    { 'id': 'ext5_g', 'title': 'EXT5_G' },
    { 'id': 'ext5_t', 'title': 'EXT5_T' },
    { 'id': 'ext6_b', 'title': 'EXT6_B' },
    { 'id': 'ext6_g', 'title': 'EXT6_G' },
    { 'id': 'ext6_t', 'title': 'EXT6_T' },
    { 'id': 'ext7_b', 'title': 'EXT7_B' },
    { 'id': 'ext7_g', 'title': 'EXT7_G' },
    { 'id': 'ext7_t', 'title': 'EXT7_T' },
    { 'id': 'extt_b', 'title': 'EXTT_B' },
    { 'id': 'extt_g', 'title': 'EXTT_G' },
    { 'id': 'extt_t', 'title': 'EXTT_T' },
    { 'id': 'tsa1_b', 'title': 'TSA1_B' },
    { 'id': 'tsa1_g', 'title': 'TSA1_G' },
    { 'id': 'tsa1_t', 'title': 'TSA1_T' },
    { 'id': 'tsa2_b', 'title': 'TSA2_B' },
    { 'id': 'tsa2_g', 'title': 'TSA2_G' },
    { 'id': 'tsa2_t', 'title': 'TSA2_T' },
    { 'id': 'tsa3_b', 'title': 'TSA3_B' },
    { 'id': 'tsa3_g', 'title': 'TSA3_G' },
    { 'id': 'tsa3_t', 'title': 'TSA3_T' },
    { 'id': 'tnr1_b', 'title': 'TNR1_B' },
    { 'id': 'tnr1_g', 'title': 'TNR1_G' },
    { 'id': 'tnr1_t', 'title': 'TNR1_T' },
]
