import instrument from '../../libraries/instrument';
import { QuestionObjectType } from '../../libraries/interfaces';


export const questions: QuestionObjectType = {
    'reg': {
        name: 'reg',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 0,
        active: function () { return (true) },
        error: ''
    },
    'dis': {
        name: 'dis',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 1,
        active: function () { return (true) },
        error: ''
    },
    'data': {
        name: 'data',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: true,
        readonly: true,
        order: 2,
        active: function () { return (true) },
        error: ''
    },
    'q2': {
        name: 'q2',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 3,
        active: function () { return (true) },
        error: ''
    },
    'inst': {
        name: 'inst',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 4,
        active: function () { return (true) },
        error: ''
    },
    'q3': {
        name: 'q3',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 5,
        active: function () { return (true) },
        error: ''
    },
    'q4': {
        name: 'q4',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 6,
        active: function () { return (true) },
        error: ''
    },
    'q5': {
        name: 'q5',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 7,
        active: function () { return (true) },
        error: ''
    },
    'q6': {
        name: 'q6',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 8,
        active: function () { return (true) },
        error: ''
    },
    'ifp1a': {
        name: 'ifp1a',
        type: 'select',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 9,
        active: function () { return (true) },
        error: ''
    },
    'ifp1b': {
        name: 'ifp1b',
        type: 'select',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 10,
        active: function () { return (true) },
        error: ''
    },
    'ifp1c': {
        name: 'ifp1c',
        type: 'select',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 11,
        active: function () { return (true) },
        error: ''
    },
    'ifp1d': {
        name: 'ifp1d',
        type: 'radio',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 12,
        active: function () { return (true) },
        error: ''
    },
    'ifp2': {
        name: 'ifp2',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 13,
        active: function () { return (true) },
        error: ''
    },
    'ifp2ay': {
        name: 'ifp2ay',
        type: 'number',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 14,
        active: function () { return (true) },
        error: ''
    },
    'ifp2am': {
        name: 'ifp2am',
        type: 'number',
        value: '-9',
        disabled: true,
        hidden: true,
        readonly: true,
        order: 15,
        active: function () { return (true) },
        error: ''
    },
    'ifp3': {
        name: 'ifp3',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 16,
        active: function () { return (true) },
        error: ''
    },
    'ifp4': {
        name: 'ifp4',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 17,
        active: function () { return (true) },
        error: ''
    },
    'ifm1': {
        name: 'ifm1',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 18,
        active: function () { return (true) },
        error: ''
    },
    'ifm2': {
        name: 'ifm2',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 19,
        active: function () { return (true) },
        error: ''
    },
    'ifm3': {
        name: 'ifm3',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 20,
        active: function () { return (true) },
        error: ''
    },
    'ifm4': {
        name: 'ifm4',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 21,
        active: function () { return (true) },
        error: ''
    },
    'ifm4_age': {
        name: 'ifm4_age',
        type: 'number',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 22,
        active: function () { return (true) },
        error: ''
    },
    'ifm5': {
        name: 'ifm5',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 23,
        active: function () { return (true) },
        error: ''
    },
    'ifm6': {
        name: 'ifm6',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 24,
        active: function () { return (true) },
        error: ''
    },
    'ifm6_other': {
        name: 'ifm6_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 25,
        active: function () { return (Number(instrument.questions.ifm6.value) == 16) },
        error: ''
    },
    'ift1': {
        name: 'ift1',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 26,
        active: function () { return (true) },
        error: ''
    },
    'ift2': {
        name: 'ift2',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 27,
        active: function () { return (true) },
        error: ''
    },
    'ift3': {
        name: 'ift3',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 28,
        active: function () { return (true) },
        error: ''
    },
    'ift4': {
        name: 'ift4',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 29,
        active: function () { return (true) },
        error: ''
    },
    'ift4_age': {
        name: 'ift4_age',
        type: 'number',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 30,
        active: function () { return (true) },
        error: ''
    },
    'ift5': {
        name: 'ift5',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 31,
        active: function () { return (true) },
        error: ''
    },
    'ift6': {
        name: 'ift6',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 32,
        active: function () { return (true) },
        error: ''
    },
    'ift6_other': {
        name: 'ift6_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 33,
        active: function () { return (Number(instrument.questions.ift6.value) == 16) },
        error: ''
    },
    'ifp4a': {
        name: 'ifp4a',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 34,
        active: function () { return (true) },
        error: ''
    },
    'ifp4b': {
        name: 'ifp4b',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 35,
        active: function () { return (true) },
        error: ''
    },
    'ifp5': {
        name: 'ifp5',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 36,
        active: function () { return (true) },
        error: ''
    },
    'fc1': {
        name: 'fc1',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 37,
        active: function () { return (true) },
        error: ''
    },
    'fc2a': {
        name: 'fc2a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 38,
        active: function () { return (Number(instrument.questions.fc1.value) > 0) },
        error: ''
    },
    'fc2b': {
        name: 'fc2b',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 39,
        active: function () { return (Number(instrument.questions.fc1.value) > 0) },
        error: ''
    },
    'fc2f': {
        name: 'fc2f',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 40,
        active: function () { return (Number(instrument.questions.fc1.value) > 0) },
        error: ''
    },
    'fc2c': {
        name: 'fc2c',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 41,
        active: function () { return (Number(instrument.questions.fc1.value) > 0) },
        error: ''
    },
    'fc2d': {
        name: 'fc2d',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 42,
        active: function () { return (Number(instrument.questions.fc1.value) > 0) },
        error: ''
    },
    'fc2e': {
        name: 'fc2e',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 43,
        active: function () { return (Number(instrument.questions.fc1.value) > 0) },
        error: ''
    },
    'fc3': {
        name: 'fc3',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 44,
        active: function () { return (true) },
        error: ''
    },
    'fc4_c1a': {
        name: 'fc4_c1a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 45,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c1b': {
        name: 'fc4_c1b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 46,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c1c': {
        name: 'fc4_c1c',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 47,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c1d': {
        name: 'fc4_c1d',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 48,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c1e': {
        name: 'fc4_c1e',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 49,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c1e_other': {
        name: 'fc4_c1e_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 50,
        active: function () { return (Number(instrument.questions.fc3.value) > 0 && Number(instrument.questions.fc4_c1e.value) == 5) },
        error: ''
    },
    'fc4_c1f': {
        name: 'fc4_c1f',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 51,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c2a': {
        name: 'fc4_c2a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 52,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c2b': {
        name: 'fc4_c2b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 53,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c2c': {
        name: 'fc4_c2c',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 54,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c2d': {
        name: 'fc4_c2d',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 55,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c2e': {
        name: 'fc4_c2e',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 56,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c2e_other': {
        name: 'fc4_c2e_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 57,
        active: function () { return (Number(instrument.questions.fc3.value) > 0 && Number(instrument.questions.fc4_c2e.value) == 5) },
        error: ''
    },
    'fc4_c2f': {
        name: 'fc4_c2f',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 58,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c3a': {
        name: 'fc4_c3a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 59,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c3b': {
        name: 'fc4_c3b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 60,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c3c': {
        name: 'fc4_c3c',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 61,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c3d': {
        name: 'fc4_c3d',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 62,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c3e': {
        name: 'fc4_c3e',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 63,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c3e_other': {
        name: 'fc4_c3e_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 64,
        active: function () { return (Number(instrument.questions.fc3.value) > 0 && Number(instrument.questions.fc4_c3e.value) == 5) },
        error: ''
    },
    'fc4_c3f': {
        name: 'fc4_c3f',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 65,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c4a': {
        name: 'fc4_c4a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 66,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c4b': {
        name: 'fc4_c4b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 67,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c4c': {
        name: 'fc4_c4c',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 68,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c4d': {
        name: 'fc4_c4d',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 69,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c4e': {
        name: 'fc4_c4e',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 70,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c4e_other': {
        name: 'fc4_c4e_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 71,
        active: function () { return (Number(instrument.questions.fc3.value) > 0 && Number(instrument.questions.fc4_c4e.value) == 5) },
        error: ''
    },
    'fc4_c4f': {
        name: 'fc4_c4f',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 72,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c5a': {
        name: 'fc4_c5a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 73,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c5b': {
        name: 'fc4_c5b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 74,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c5c': {
        name: 'fc4_c5c',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 75,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c5d': {
        name: 'fc4_c5d',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 76,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c5e': {
        name: 'fc4_c5e',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 77,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'fc4_c5e_other': {
        name: 'fc4_c5e_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 78,
        active: function () { return (Number(instrument.questions.fc3.value) > 0 && Number(instrument.questions.fc4_c5e.value) == 5) },
        error: ''
    },
    'fc4_c5f': {
        name: 'fc4_c5f',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 79,
        active: function () { return (Number(instrument.questions.fc3.value) > 0) },
        error: ''
    },
    'ex1': {
        name: 'ex1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 80,
        active: function () { return (true) },
        error: ''
    },
    'ex2': {
        name: 'ex2',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 81,
        active: function () { return (Number(instrument.questions.ex1.value) == 1) },
        error: ''
    },
    'ex3_c1a': {
        name: 'ex3_c1a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 82,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c1b': {
        name: 'ex3_c1b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 83,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c1c': {
        name: 'ex3_c1c',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 84,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c1d': {
        name: 'ex3_c1d',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 85,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c1d_other': {
        name: 'ex3_c1d_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 86,
        active: function () { return (Number(instrument.questions.ex2.value) > 0 && Number(instrument.questions.ex3_c1d.value) == 10) },
        error: ''
    },
    'ex3_c2a': {
        name: 'ex3_c2a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 87,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c2b': {
        name: 'ex3_c2b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 88,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c2c': {
        name: 'ex3_c2c',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 89,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c2d': {
        name: 'ex3_c2d',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 90,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c2d_other': {
        name: 'ex3_c2d_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 91,
        active: function () { return (Number(instrument.questions.ex2.value) > 0 && Number(instrument.questions.ex3_c2d.value) == 10) },
        error: ''
    },
    'ex3_c3a': {
        name: 'ex3_c3a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 92,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c3b': {
        name: 'ex3_c3b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 93,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c3c': {
        name: 'ex3_c3c',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 94,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c3d': {
        name: 'ex3_c3d',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 95,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c3d_other': {
        name: 'ex3_c3d_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 96,
        active: function () { return (Number(instrument.questions.ex2.value) > 0 && Number(instrument.questions.ex3_c3d.value) == 10) },
        error: ''
    },
    'ex3_c4a': {
        name: 'ex3_c4a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 97,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c4b': {
        name: 'ex3_c4b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 98,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c4c': {
        name: 'ex3_c4c',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 99,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c4d': {
        name: 'ex3_c4d',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 100,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c4d_other': {
        name: 'ex3_c4d_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 101,
        active: function () { return (Number(instrument.questions.ex2.value) > 0 && Number(instrument.questions.ex3_c4d.value) == 10) },
        error: ''
    },
    'ex3_c5a': {
        name: 'ex3_c5a',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 102,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c5b': {
        name: 'ex3_c5b',
        type: 'number',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 103,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c5c': {
        name: 'ex3_c5c',
        type: 'radio',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 104,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c5d': {
        name: 'ex3_c5d',
        type: 'select',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 105,
        active: function () { return (Number(instrument.questions.ex2.value) > 0) },
        error: ''
    },
    'ex3_c5d_other': {
        name: 'ex3_c5d_other',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 106,
        active: function () { return (Number(instrument.questions.ex2.value) > 0 && Number(instrument.questions.ex3_c5d.value) == 10) },
        error: ''
    },
    'qs1': {
        name: 'qs1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 107,
        active: function () { return (true) },
        error: ''
    },
    'qs2': {
        name: 'qs2',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 108,
        active: function () { return (true) },
        error: ''
    },
    'qs3': {
        name: 'qs3',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 109,
        active: function () { return (true) },
        error: ''
    },
    'qs3a': {
        name: 'qs3a',
        type: 'input',
        value: '-7',
        disabled: true,
        hidden: false,
        readonly: false,
        order: 110,
        active: function () { return (Number(instrument.questions.qs3.value) == 1) },
        error: ''
    },
    'qs4': {
        name: 'qs4',
        type: 'number',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 111,
        active: function () { return (true) },
        error: ''
    },
    'qs5a': {
        name: 'qs5a',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 112,
        active: function () { return (true) },
        error: ''
    },
    'qs5b': {
        name: 'qs5b',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 113,
        active: function () { return (true) },
        error: ''
    },
    'qs5c': {
        name: 'qs5c',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 114,
        active: function () { return (true) },
        error: ''
    },
    'qs5d': {
        name: 'qs5d',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 115,
        active: function () { return (true) },
        error: ''
    },
    'qs6': {
        name: 'qs6',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 116,
        active: function () { return (true) },
        error: ''
    },
};

export const questionOrder: Array<string> = [
    'reg', 'dis', 'data', 'q2', 'inst', 'q3', 'q4', 'q5', 'q6', 'ifp1a', 'ifp1b', 'ifp1c', 'ifp1d', 'ifp2',
    'ifp2ay', 'ifp2am', 'ifp3', 'ifp4', 'ifm1', 'ifm2', 'ifm3', 'ifm4', 'ifm4_age', 'ifm5', 'ifm6', 'ifm6_other',
    'ift1', 'ift2', 'ift3', 'ift4', 'ift4_age', 'ift5', 'ift6', 'ift6_other', 'ifp4a', 'ifp4b', 'ifp5', 'fc1',
    'fc2a', 'fc2b', 'fc2f', 'fc2c', 'fc2d', 'fc2e', 'fc3', 'fc4_c1a', 'fc4_c1b', 'fc4_c1c', 'fc4_c1d', 'fc4_c1e',
    'fc4_c1e_other', 'fc4_c1f', 'fc4_c2a', 'fc4_c2b', 'fc4_c2c', 'fc4_c2d', 'fc4_c2e', 'fc4_c2e_other',
    'fc4_c2f', 'fc4_c3a', 'fc4_c3b', 'fc4_c3c', 'fc4_c3d', 'fc4_c3e', 'fc4_c3e_other', 'fc4_c3f', 'fc4_c4a',
    'fc4_c4b', 'fc4_c4c', 'fc4_c4d', 'fc4_c4e', 'fc4_c4e_other', 'fc4_c4f', 'fc4_c5a', 'fc4_c5b', 'fc4_c5c',
    'fc4_c5d', 'fc4_c5e', 'fc4_c5e_other', 'fc4_c5f', 'ex1', 'ex2', 'ex3_c1a', 'ex3_c1b', 'ex3_c1c', 'ex3_c1d',
    'ex3_c1d_other', 'ex3_c2a', 'ex3_c2b', 'ex3_c2c', 'ex3_c2d', 'ex3_c2d_other', 'ex3_c3a', 'ex3_c3b',
    'ex3_c3c', 'ex3_c3d', 'ex3_c3d_other', 'ex3_c4a', 'ex3_c4b', 'ex3_c4c', 'ex3_c4d', 'ex3_c4d_other',
    'ex3_c5a', 'ex3_c5b', 'ex3_c5c', 'ex3_c5d', 'ex3_c5d_other', 'qs1', 'qs2', 'qs3', 'qs3a', 'qs4', 'qs5a',
    'qs5b', 'qs5c', 'qs5d', 'qs6'
];

export const exportHeader: Array<{ id: string; title: string }> = [
    { 'id': 'reg', 'title': 'REG' },
    { 'id': 'dis', 'title': 'DIS' },
    { 'id': 'data', 'title': 'DATA' },
    { 'id': 'q2', 'title': 'Q2' },
    { 'id': 'inst', 'title': 'INST' },
    { 'id': 'q3', 'title': 'Q3' },
    { 'id': 'q4', 'title': 'Q4' },
    { 'id': 'q5', 'title': 'Q5' },
    { 'id': 'q6', 'title': 'Q6' },
    { 'id': 'ifp1a', 'title': 'IFP1A' },
    { 'id': 'ifp1b', 'title': 'IFP1B' },
    { 'id': 'ifp1c', 'title': 'IFP1C' },
    { 'id': 'ifp1d', 'title': 'IFP1D' },
    { 'id': 'ifp2', 'title': 'IFP2' },
    { 'id': 'ifp2ay', 'title': 'IFP2AY' },
    { 'id': 'ifp2am', 'title': 'IFP2AM' },
    { 'id': 'ifp3', 'title': 'IFP3' },
    { 'id': 'ifp4', 'title': 'IFP4' },
    { 'id': 'ifm1', 'title': 'IFM1' },
    { 'id': 'ifm2', 'title': 'IFM2' },
    { 'id': 'ifm3', 'title': 'IFM3' },
    { 'id': 'ifm4', 'title': 'IFM4' },
    { 'id': 'ifm4_age', 'title': 'IFM4_AGE' },
    { 'id': 'ifm5', 'title': 'IFM5' },
    { 'id': 'ifm6', 'title': 'IFM6' },
    { 'id': 'ifm6_other', 'title': 'IFM6_OTHER' },
    { 'id': 'ift1', 'title': 'IFT1' },
    { 'id': 'ift2', 'title': 'IFT2' },
    { 'id': 'ift3', 'title': 'IFT3' },
    { 'id': 'ift4', 'title': 'IFT4' },
    { 'id': 'ift4_age', 'title': 'IFT4_AGE' },
    { 'id': 'ift5', 'title': 'IFT5' },
    { 'id': 'ift6', 'title': 'IFT6' },
    { 'id': 'ift6_other', 'title': 'IFT6_OTHER' },
    { 'id': 'ifp4a', 'title': 'IFP4A' },
    { 'id': 'ifp4b', 'title': 'IFP4B' },
    { 'id': 'ifp5', 'title': 'IFP5' },
    { 'id': 'fc1', 'title': 'FC1' },
    { 'id': 'fc2a', 'title': 'FC2A' },
    { 'id': 'fc2b', 'title': 'FC2B' },
    { 'id': 'fc2f', 'title': 'FC2F' },
    { 'id': 'fc2c', 'title': 'FC2C' },
    { 'id': 'fc2d', 'title': 'FC2D' },
    { 'id': 'fc2e', 'title': 'FC2E' },
    { 'id': 'fc3', 'title': 'FC3' },
    { 'id': 'fc4_c1a', 'title': 'FC4_C1A' },
    { 'id': 'fc4_c1b', 'title': 'FC4_C1B' },
    { 'id': 'fc4_c1c', 'title': 'FC4_C1C' },
    { 'id': 'fc4_c1d', 'title': 'FC4_C1D' },
    { 'id': 'fc4_c1e', 'title': 'FC4_C1E' },
    { 'id': 'fc4_c1e_other', 'title': 'FC4_C1E_OTHER' },
    { 'id': 'fc4_c1f', 'title': 'FC4_C1F' },
    { 'id': 'fc4_c2a', 'title': 'FC4_C2A' },
    { 'id': 'fc4_c2b', 'title': 'FC4_C2B' },
    { 'id': 'fc4_c2c', 'title': 'FC4_C2C' },
    { 'id': 'fc4_c2d', 'title': 'FC4_C2D' },
    { 'id': 'fc4_c2e', 'title': 'FC4_C2E' },
    { 'id': 'fc4_c2e_other', 'title': 'FC4_C2E_OTHER' },
    { 'id': 'fc4_c2f', 'title': 'FC4_C2F' },
    { 'id': 'fc4_c3a', 'title': 'FC4_C3A' },
    { 'id': 'fc4_c3b', 'title': 'FC4_C3B' },
    { 'id': 'fc4_c3c', 'title': 'FC4_C3C' },
    { 'id': 'fc4_c3d', 'title': 'FC4_C3D' },
    { 'id': 'fc4_c3e', 'title': 'FC4_C3E' },
    { 'id': 'fc4_c3e_other', 'title': 'FC4_C3E_OTHER' },
    { 'id': 'fc4_c3f', 'title': 'FC4_C3F' },
    { 'id': 'fc4_c4a', 'title': 'FC4_C4A' },
    { 'id': 'fc4_c4b', 'title': 'FC4_C4B' },
    { 'id': 'fc4_c4c', 'title': 'FC4_C4C' },
    { 'id': 'fc4_c4d', 'title': 'FC4_C4D' },
    { 'id': 'fc4_c4e', 'title': 'FC4_C4E' },
    { 'id': 'fc4_c4e_other', 'title': 'FC4_C4E_OTHER' },
    { 'id': 'fc4_c4f', 'title': 'FC4_C4F' },
    { 'id': 'fc4_c5a', 'title': 'FC4_C5A' },
    { 'id': 'fc4_c5b', 'title': 'FC4_C5B' },
    { 'id': 'fc4_c5c', 'title': 'FC4_C5C' },
    { 'id': 'fc4_c5d', 'title': 'FC4_C5D' },
    { 'id': 'fc4_c5e', 'title': 'FC4_C5E' },
    { 'id': 'fc4_c5e_other', 'title': 'FC4_C5E_OTHER' },
    { 'id': 'fc4_c5f', 'title': 'FC4_C5F' },
    { 'id': 'ex1', 'title': 'EX1' },
    { 'id': 'ex2', 'title': 'EX2' },
    { 'id': 'ex3_c1a', 'title': 'EX3_C1A' },
    { 'id': 'ex3_c1b', 'title': 'EX3_C1B' },
    { 'id': 'ex3_c1c', 'title': 'EX3_C1C' },
    { 'id': 'ex3_c1d', 'title': 'EX3_C1D' },
    { 'id': 'ex3_c1d_other', 'title': 'EX3_C1D_OTHER' },
    { 'id': 'ex3_c2a', 'title': 'EX3_C2A' },
    { 'id': 'ex3_c2b', 'title': 'EX3_C2B' },
    { 'id': 'ex3_c2c', 'title': 'EX3_C2C' },
    { 'id': 'ex3_c2d', 'title': 'EX3_C2D' },
    { 'id': 'ex3_c2d_other', 'title': 'EX3_C2D_OTHER' },
    { 'id': 'ex3_c3a', 'title': 'EX3_C3A' },
    { 'id': 'ex3_c3b', 'title': 'EX3_C3B' },
    { 'id': 'ex3_c3c', 'title': 'EX3_C3C' },
    { 'id': 'ex3_c3d', 'title': 'EX3_C3D' },
    { 'id': 'ex3_c3d_other', 'title': 'EX3_C3D_OTHER' },
    { 'id': 'ex3_c4a', 'title': 'EX3_C4A' },
    { 'id': 'ex3_c4b', 'title': 'EX3_C4B' },
    { 'id': 'ex3_c4c', 'title': 'EX3_C4C' },
    { 'id': 'ex3_c4d', 'title': 'EX3_C4D' },
    { 'id': 'ex3_c4d_other', 'title': 'EX3_C4D_OTHER' },
    { 'id': 'ex3_c5a', 'title': 'EX3_C5A' },
    { 'id': 'ex3_c5b', 'title': 'EX3_C5B' },
    { 'id': 'ex3_c5c', 'title': 'EX3_C5C' },
    { 'id': 'ex3_c5d', 'title': 'EX3_C5D' },
    { 'id': 'ex3_c5d_other', 'title': 'EX3_C5D_OTHER' },
    { 'id': 'qs1', 'title': 'QS1' },
    { 'id': 'qs2', 'title': 'QS2' },
    { 'id': 'qs3', 'title': 'QS3' },
    { 'id': 'qs3a', 'title': 'QS3A' },
    { 'id': 'qs4', 'title': 'QS4' },
    { 'id': 'qs5a', 'title': 'QS5A' },
    { 'id': 'qs5b', 'title': 'QS5B' },
    { 'id': 'qs5c', 'title': 'QS5C' },
    { 'id': 'qs5d', 'title': 'QS5D' },
    { 'id': 'qs6', 'title': 'QS6' },
];
