import instrument from '../../libraries/instrument';
import { QuestionObjectType } from '../../libraries/interfaces';


export const questions: QuestionObjectType = {
    'q1': {
        name: 'q1',
        type: 'input',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 0,
        active: function () { return (true) },
        error: ''
    },
    'q2': {
        name: 'q2',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 1,
        active: function () { return (true) },
        error: ''
    },
    'i2': {
        name: 'i2',
        type: 'select',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 2,
        active: function () { return (true) },
        error: ''
    },
    'i1': {
        name: 'i1',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 3,
        active: function () { return (true) },
        error: ''
    },
    'i3': {
        name: 'i3',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 4,
        active: function () { return (true) },
        error: ''
    },
    'i4a': {
        name: 'i4a',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 5,
        active: function () { return (true) },
        error: ''
    },
    'i4b': {
        name: 'i4b',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 6,
        active: function () { return (true) },
        error: ''
    },
    'i4c': {
        name: 'i4c',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 7,
        active: function () { return (true) },
        error: ''
    },
    'i4d': {
        name: 'i4d',
        type: 'input',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 8,
        active: function () { return (true) },
        error: ''
    },
    // TODO -- input sau select?
    'i9': {
        name: 'i9',
        type: 'select',
        value: '-9',
        disabled: true,
        hidden: false,
        readonly: true,
        order: 9,
        active: function () { return (true) },
        error: ''
    },
    'e1': {
        name: 'e1',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 10,
        active: function () { return (true) },
        error: ''
    },
    'e1_n': {
        name: 'e1_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 11,
        active: function () { return (true) },
        error: ''
    },
    'e2': {
        name: 'e2',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 12,
        active: function () { return (true) },
        error: ''
    },
    'e2_n': {
        name: 'e2_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 13,
        active: function () { return (true) },
        error: ''
    },
    'e3': {
        name: 'e3',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 14,
        active: function () { return (true) },
        error: ''
    },
    'e3_n': {
        name: 'e3_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 15,
        active: function () { return (true) },
        error: ''
    },
    'e4': {
        name: 'e4',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 16,
        active: function () { return (true) },
        error: ''
    },
    'e4_n': {
        name: 'e4_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 17,
        active: function () { return (true) },
        error: ''
    },
    'e5': {
        name: 'e5',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 18,
        active: function () { return (true) },
        error: ''
    },
    'e5_n': {
        name: 'e5_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 19,
        active: function () { return (true) },
        error: ''
    },
    'e6': {
        name: 'e6',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 20,
        active: function () { return (true) },
        error: ''
    },
    'e6_n': {
        name: 'e6_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 21,
        active: function () { return (true) },
        error: ''
    },
    'e7': {
        name: 'e7',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 22,
        active: function () { return (true) },
        error: ''
    },
    'e7_n': {
        name: 'e7_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 23,
        active: function () { return (true) },
        error: ''
    },
    'e8': {
        name: 'e8',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 24,
        active: function () { return (true) },
        error: ''
    },
    'e8_n': {
        name: 'e8_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 25,
        active: function () { return (true) },
        error: ''
    },
    'e9': {
        name: 'e9',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 26,
        active: function () { return (true) },
        error: ''
    },
    'e9_n': {
        name: 'e9_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 27,
        active: function () { return (true) },
        error: ''
    },
    'e10': {
        name: 'e10',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 28,
        active: function () { return (true) },
        error: ''
    },
    'e10_n': {
        name: 'e10_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 29,
        active: function () { return (true) },
        error: ''
    },
    'e11': {
        name: 'e11',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 30,
        active: function () { return (true) },
        error: ''
    },
    'e11_n': {
        name: 'e11_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 31,
        active: function () { return (true) },
        error: ''
    },
    'e12': {
        name: 'e12',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 32,
        active: function () { return (true) },
        error: ''
    },
    'e12_n': {
        name: 'e12_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 33,
        active: function () { return (true) },
        error: ''
    },
    'e13': {
        name: 'e13',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 34,
        active: function () { return (true) },
        error: ''
    },
    'e13_n': {
        name: 'e13_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 35,
        active: function () { return (true) },
        error: ''
    },
    'e14': {
        name: 'e14',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 36,
        active: function () { return (true) },
        error: ''
    },
    'e14_n': {
        name: 'e14_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 37,
        active: function () { return (true) },
        error: ''
    },
    'e15': {
        name: 'e15',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 38,
        active: function () { return (true) },
        error: ''
    },
    'e15_n': {
        name: 'e15_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 39,
        active: function () { return (true) },
        error: ''
    },
    'e16': {
        name: 'e16',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 40,
        active: function () { return (true) },
        error: ''
    },
    'e16_n': {
        name: 'e16_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 41,
        active: function () { return (true) },
        error: ''
    },
    'e17': {
        name: 'e17',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 42,
        active: function () { return (true) },
        error: ''
    },
    'e17_n': {
        name: 'e17_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 43,
        active: function () { return (true) },
        error: ''
    },
    'e18': {
        name: 'e18',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 44,
        active: function () { return (true) },
        error: ''
    },
    'e18_n': {
        name: 'e18_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 45,
        active: function () { return (true) },
        error: ''
    },
    'e19': {
        name: 'e19',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 46,
        active: function () { return (true) },
        error: ''
    },
    'e19_n': {
        name: 'e19_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 47,
        active: function () { return (true) },
        error: ''
    },
    'e20': {
        name: 'e20',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 48,
        active: function () { return (true) },
        error: ''
    },
    'e20_n': {
        name: 'e20_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 49,
        active: function () { return (true) },
        error: ''
    },
    'e21': {
        name: 'e21',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 50,
        active: function () { return (true) },
        error: ''
    },
    'e21_n': {
        name: 'e21_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 51,
        active: function () { return (true) },
        error: ''
    },
    'e22': {
        name: 'e22',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 52,
        active: function () { return (true) },
        error: ''
    },
    'e22_n': {
        name: 'e22_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 53,
        active: function () { return (true) },
        error: ''
    },
    'e23': {
        name: 'e23',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 54,
        active: function () { return (true) },
        error: ''
    },
    'e23_n': {
        name: 'e23_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 55,
        active: function () { return (true) },
        error: ''
    },
    'e24': {
        name: 'e24',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 56,
        active: function () { return (true) },
        error: ''
    },
    'e24_n': {
        name: 'e24_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 57,
        active: function () { return (true) },
        error: ''
    },
    'e25': {
        name: 'e25',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 58,
        active: function () { return (true) },
        error: ''
    },
    'e25_n': {
        name: 'e25_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 59,
        active: function () { return (true) },
        error: ''
    },
    'e26': {
        name: 'e26',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 60,
        active: function () { return (true) },
        error: ''
    },
    'e26_n': {
        name: 'e26_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 61,
        active: function () { return (true) },
        error: ''
    },
    'e27': {
        name: 'e27',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 62,
        active: function () { return (true) },
        error: ''
    },
    'e27_n': {
        name: 'e27_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 63,
        active: function () { return (true) },
        error: ''
    },
    'e28': {
        name: 'e28',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 64,
        active: function () { return (true) },
        error: ''
    },
    'e28_n': {
        name: 'e28_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 65,
        active: function () { return (true) },
        error: ''
    },
    'e29': {
        name: 'e29',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 66,
        active: function () { return (true) },
        error: ''
    },
    'e29_n': {
        name: 'e29_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 67,
        active: function () { return (true) },
        error: ''
    },
    'e30': {
        name: 'e30',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 68,
        active: function () { return (true) },
        error: ''
    },
    'e30_n': {
        name: 'e30_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 69,
        active: function () { return (true) },
        error: ''
    },
    'e31': {
        name: 'e31',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 70,
        active: function () { return (true) },
        error: ''
    },
    'e31_n': {
        name: 'e31_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 71,
        active: function () { return (true) },
        error: ''
    },
    'e32': {
        name: 'e32',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 72,
        active: function () { return (true) },
        error: ''
    },
    'e32_n': {
        name: 'e32_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 73,
        active: function () { return (true) },
        error: ''
    },
    'e33': {
        name: 'e33',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 74,
        active: function () { return (true) },
        error: ''
    },
    'e33_n': {
        name: 'e33_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 75,
        active: function () { return (true) },
        error: ''
    },
    'e34': {
        name: 'e34',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 76,
        active: function () { return (true) },
        error: ''
    },
    'e34_n': {
        name: 'e34_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 77,
        active: function () { return (true) },
        error: ''
    },
    'e35': {
        name: 'e35',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 78,
        active: function () { return (true) },
        error: ''
    },
    'e35_n': {
        name: 'e35_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 79,
        active: function () { return (true) },
        error: ''
    },
    'e36': {
        name: 'e36',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 80,
        active: function () { return (true) },
        error: ''
    },
    'e36_n': {
        name: 'e36_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 81,
        active: function () { return (true) },
        error: ''
    },
    'e37': {
        name: 'e37',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 82,
        active: function () { return (true) },
        error: ''
    },
    'e37_n': {
        name: 'e37_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 83,
        active: function () { return (true) },
        error: ''
    },
    'e38': {
        name: 'e38',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 84,
        active: function () { return (true) },
        error: ''
    },
    'e38_n': {
        name: 'e38_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 85,
        active: function () { return (true) },
        error: ''
    },
    'e39': {
        name: 'e39',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 86,
        active: function () { return (true) },
        error: ''
    },
    'e39_n': {
        name: 'e39_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 87,
        active: function () { return (true) },
        error: ''
    },
    'e40': {
        name: 'e40',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 88,
        active: function () { return (true) },
        error: ''
    },
    'e40_n': {
        name: 'e40_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 89,
        active: function () { return (true) },
        error: ''
    },
    'e41': {
        name: 'e41',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 90,
        active: function () { return (true) },
        error: ''
    },
    'e41_n': {
        name: 'e41_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 91,
        active: function () { return (true) },
        error: ''
    },
    'e42': {
        name: 'e42',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 92,
        active: function () { return (true) },
        error: ''
    },
    'e42_n': {
        name: 'e42_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 93,
        active: function () { return (true) },
        error: ''
    },
    'e43': {
        name: 'e43',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 94,
        active: function () { return (true) },
        error: ''
    },
    'e43_n': {
        name: 'e43_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 95,
        active: function () { return (true) },
        error: ''
    },
    'e44': {
        name: 'e44',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 96,
        active: function () { return (true) },
        error: ''
    },
    'e44_n': {
        name: 'e44_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 97,
        active: function () { return (true) },
        error: ''
    },
    'e45': {
        name: 'e45',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 98,
        active: function () { return (true) },
        error: ''
    },
    'e45_n': {
        name: 'e45_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 99,
        active: function () { return (true) },
        error: ''
    },
    'e46': {
        name: 'e46',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 100,
        active: function () { return (true) },
        error: ''
    },
    'e46_n': {
        name: 'e46_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 101,
        active: function () { return (true) },
        error: ''
    },
    'e47': {
        name: 'e47',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 102,
        active: function () { return (true) },
        error: ''
    },
    'e47_n': {
        name: 'e47_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 103,
        active: function () { return (true) },
        error: ''
    },
    'e48': {
        name: 'e48',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 104,
        active: function () { return (true) },
        error: ''
    },
    'e48_n': {
        name: 'e48_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 105,
        active: function () { return (true) },
        error: ''
    },
    'e49': {
        name: 'e49',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 106,
        active: function () { return (true) },
        error: ''
    },
    'e49_n': {
        name: 'e49_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 107,
        active: function () { return (true) },
        error: ''
    },
    'e50': {
        name: 'e50',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 108,
        active: function () { return (true) },
        error: ''
    },
    'e50_n': {
        name: 'e50_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 109,
        active: function () { return (true) },
        error: ''
    },
    'e51': {
        name: 'e51',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 110,
        active: function () { return (true) },
        error: ''
    },
    'e51_n': {
        name: 'e51_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 111,
        active: function () { return (true) },
        error: ''
    },
    'e52': {
        name: 'e52',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 112,
        active: function () { return (true) },
        error: ''
    },
    'e52_n': {
        name: 'e52_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 113,
        active: function () { return (true) },
        error: ''
    },
    'e53': {
        name: 'e53',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 114,
        active: function () { return (true) },
        error: ''
    },
    'e53_n': {
        name: 'e53_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 115,
        active: function () { return (true) },
        error: ''
    },
    'e54': {
        name: 'e54',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 116,
        active: function () { return (true) },
        error: ''
    },
    'e54_n': {
        name: 'e54_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 117,
        active: function () { return (true) },
        error: ''
    },
    'e55': {
        name: 'e55',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 118,
        active: function () { return (true) },
        error: ''
    },
    'e55_n': {
        name: 'e55_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 119,
        active: function () { return (true) },
        error: ''
    },
    'e56': {
        name: 'e56',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 120,
        active: function () { return (true) },
        error: ''
    },
    'e56_n': {
        name: 'e56_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 121,
        active: function () { return (true) },
        error: ''
    },
    'e57': {
        name: 'e57',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 122,
        active: function () { return (true) },
        error: ''
    },
    'e57_n': {
        name: 'e57_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 123,
        active: function () { return (true) },
        error: ''
    },
    'e58': {
        name: 'e58',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 124,
        active: function () { return (true) },
        error: ''
    },
    'e58_n': {
        name: 'e58_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 125,
        active: function () { return (true) },
        error: ''
    },
    'e59': {
        name: 'e59',
        type: 'radio',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 126,
        active: function () { return (true) },
        error: ''
    },
    'e59_n': {
        name: 'e59_n',
        type: 'textarea',
        value: '-9',
        disabled: false,
        hidden: false,
        readonly: false,
        order: 127,
        active: function () { return (true) },
        error: ''
    },
};

export const questionOrder: Array<string> = [
    'q1', 'q2', 'i2', 'i1', 'i3', 'i4a', 'i4b', 'i4c', 'i4d', 'i9', 'e1', 'e1_n', 'e2', 'e2_n', 'e3', 'e3_n',
    'e4', 'e4_n', 'e5', 'e5_n', 'e6', 'e6_n', 'e7', 'e7_n', 'e8', 'e8_n', 'e9', 'e9_n', 'e10', 'e10_n', 'e11',
    'e11_n', 'e12', 'e12_n', 'e13', 'e13_n', 'e14', 'e14_n', 'e15', 'e15_n', 'e16', 'e16_n', 'e17', 'e17_n',
    'e18', 'e18_n', 'e19', 'e19_n', 'e20', 'e20_n', 'e21', 'e21_n', 'e22', 'e22_n', 'e23', 'e23_n', 'e24',
    'e24_n', 'e25', 'e25_n', 'e26', 'e26_n', 'e27', 'e27_n', 'e28', 'e28_n', 'e29', 'e29_n', 'e30', 'e30_n',
    'e31', 'e31_n', 'e32', 'e32_n', 'e33', 'e33_n', 'e34', 'e34_n', 'e35', 'e35_n', 'e36', 'e36_n', 'e37',
    'e37_n', 'e38', 'e38_n', 'e39', 'e39_n', 'e40', 'e40_n', 'e41', 'e41_n', 'e42', 'e42_n', 'e43', 'e43_n',
    'e44', 'e44_n', 'e45', 'e45_n', 'e46', 'e46_n', 'e47', 'e47_n', 'e48', 'e48_n', 'e49', 'e49_n', 'e50',
    'e50_n', 'e51', 'e51_n', 'e52', 'e52_n', 'e53', 'e53_n', 'e54', 'e54_n', 'e55', 'e55_n', 'e56', 'e56_n',
    'e57', 'e57_n', 'e58', 'e58_n', 'e59', 'e59_n'
];

export const exportHeader: Array<{ id: string; title: string }> = [
    { 'id': 'q1', 'title': 'Q1' },
    { 'id': 'q2', 'title': 'Q2' },
    { 'id': 'i2', 'title': 'I2' },
    { 'id': 'i1', 'title': 'I1' },
    { 'id': 'i3', 'title': 'I3' },
    { 'id': 'i4a', 'title': 'I4A' },
    { 'id': 'i4b', 'title': 'I4B' },
    { 'id': 'i4c', 'title': 'I4C' },
    { 'id': 'i4d', 'title': 'I4D' },
    { 'id': 'i9', 'title': 'I9' },
    { 'id': 'e1', 'title': 'E1' },
    { 'id': 'e1_n', 'title': 'E1_N' },
    { 'id': 'e2', 'title': 'E2' },
    { 'id': 'e2_n', 'title': 'E2_N' },
    { 'id': 'e3', 'title': 'E3' },
    { 'id': 'e3_n', 'title': 'E3_N' },
    { 'id': 'e4', 'title': 'E4' },
    { 'id': 'e4_n', 'title': 'E4_N' },
    { 'id': 'e5', 'title': 'E5' },
    { 'id': 'e5_n', 'title': 'E5_N' },
    { 'id': 'e6', 'title': 'E6' },
    { 'id': 'e6_n', 'title': 'E6_N' },
    { 'id': 'e7', 'title': 'E7' },
    { 'id': 'e7_n', 'title': 'E7_N' },
    { 'id': 'e8', 'title': 'E8' },
    { 'id': 'e8_n', 'title': 'E8_N' },
    { 'id': 'e9', 'title': 'E9' },
    { 'id': 'e9_n', 'title': 'E9_N' },
    { 'id': 'e10', 'title': 'E10' },
    { 'id': 'e10_n', 'title': 'E10_N' },
    { 'id': 'e11', 'title': 'E11' },
    { 'id': 'e11_n', 'title': 'E11_N' },
    { 'id': 'e12', 'title': 'E12' },
    { 'id': 'e12_n', 'title': 'E12_N' },
    { 'id': 'e13', 'title': 'E13' },
    { 'id': 'e13_n', 'title': 'E13_N' },
    { 'id': 'e14', 'title': 'E14' },
    { 'id': 'e14_n', 'title': 'E14_N' },
    { 'id': 'e15', 'title': 'E15' },
    { 'id': 'e15_n', 'title': 'E15_N' },
    { 'id': 'e16', 'title': 'E16' },
    { 'id': 'e16_n', 'title': 'E16_N' },
    { 'id': 'e17', 'title': 'E17' },
    { 'id': 'e17_n', 'title': 'E17_N' },
    { 'id': 'e18', 'title': 'E18' },
    { 'id': 'e18_n', 'title': 'E18_N' },
    { 'id': 'e19', 'title': 'E19' },
    { 'id': 'e19_n', 'title': 'E19_N' },
    { 'id': 'e20', 'title': 'E20' },
    { 'id': 'e20_n', 'title': 'E20_N' },
    { 'id': 'e21', 'title': 'E21' },
    { 'id': 'e21_n', 'title': 'E21_N' },
    { 'id': 'e22', 'title': 'E22' },
    { 'id': 'e22_n', 'title': 'E22_N' },
    { 'id': 'e23', 'title': 'E23' },
    { 'id': 'e23_n', 'title': 'E23_N' },
    { 'id': 'e24', 'title': 'E24' },
    { 'id': 'e24_n', 'title': 'E24_N' },
    { 'id': 'e25', 'title': 'E25' },
    { 'id': 'e25_n', 'title': 'E25_N' },
    { 'id': 'e26', 'title': 'E26' },
    { 'id': 'e26_n', 'title': 'E26_N' },
    { 'id': 'e27', 'title': 'E27' },
    { 'id': 'e27_n', 'title': 'E27_N' },
    { 'id': 'e28', 'title': 'E28' },
    { 'id': 'e28_n', 'title': 'E28_N' },
    { 'id': 'e29', 'title': 'E29' },
    { 'id': 'e29_n', 'title': 'E29_N' },
    { 'id': 'e30', 'title': 'E30' },
    { 'id': 'e30_n', 'title': 'E30_N' },
    { 'id': 'e31', 'title': 'E31' },
    { 'id': 'e31_n', 'title': 'E31_N' },
    { 'id': 'e32', 'title': 'E32' },
    { 'id': 'e32_n', 'title': 'E32_N' },
    { 'id': 'e33', 'title': 'E33' },
    { 'id': 'e33_n', 'title': 'E33_N' },
    { 'id': 'e34', 'title': 'E34' },
    { 'id': 'e34_n', 'title': 'E34_N' },
    { 'id': 'e35', 'title': 'E35' },
    { 'id': 'e35_n', 'title': 'E35_N' },
    { 'id': 'e36', 'title': 'E36' },
    { 'id': 'e36_n', 'title': 'E36_N' },
    { 'id': 'e37', 'title': 'E37' },
    { 'id': 'e37_n', 'title': 'E37_N' },
    { 'id': 'e38', 'title': 'E38' },
    { 'id': 'e38_n', 'title': 'E38_N' },
    { 'id': 'e39', 'title': 'E39' },
    { 'id': 'e39_n', 'title': 'E39_N' },
    { 'id': 'e40', 'title': 'E40' },
    { 'id': 'e40_n', 'title': 'E40_N' },
    { 'id': 'e41', 'title': 'E41' },
    { 'id': 'e41_n', 'title': 'E41_N' },
    { 'id': 'e42', 'title': 'E42' },
    { 'id': 'e42_n', 'title': 'E42_N' },
    { 'id': 'e43', 'title': 'E43' },
    { 'id': 'e43_n', 'title': 'E43_N' },
    { 'id': 'e44', 'title': 'E44' },
    { 'id': 'e44_n', 'title': 'E44_N' },
    { 'id': 'e45', 'title': 'E45' },
    { 'id': 'e45_n', 'title': 'E45_N' },
    { 'id': 'e46', 'title': 'E46' },
    { 'id': 'e46_n', 'title': 'E46_N' },
    { 'id': 'e47', 'title': 'E47' },
    { 'id': 'e47_n', 'title': 'E47_N' },
    { 'id': 'e48', 'title': 'E48' },
    { 'id': 'e48_n', 'title': 'E48_N' },
    { 'id': 'e49', 'title': 'E49' },
    { 'id': 'e49_n', 'title': 'E49_N' },
    { 'id': 'e50', 'title': 'E50' },
    { 'id': 'e50_n', 'title': 'E50_N' },
    { 'id': 'e51', 'title': 'E51' },
    { 'id': 'e51_n', 'title': 'E51_N' },
    { 'id': 'e52', 'title': 'E52' },
    { 'id': 'e52_n', 'title': 'E52_N' },
    { 'id': 'e53', 'title': 'E53' },
    { 'id': 'e53_n', 'title': 'E53_N' },
    { 'id': 'e54', 'title': 'E54' },
    { 'id': 'e54_n', 'title': 'E54_N' },
    { 'id': 'e55', 'title': 'E55' },
    { 'id': 'e55_n', 'title': 'E55_N' },
    { 'id': 'e56', 'title': 'E56' },
    { 'id': 'e56_n', 'title': 'E56_N' },
    { 'id': 'e57', 'title': 'E57' },
    { 'id': 'e57_n', 'title': 'E57_N' },
    { 'id': 'e58', 'title': 'E58' },
    { 'id': 'e58_n', 'title': 'E58_N' },
    { 'id': 'e59', 'title': 'E59' },
    { 'id': 'e59_n', 'title': 'E59_N' },
];
